import { IMG, sans, serif, ar, type Plantilla } from './tipos'

// ─── Datos ───────────────────────────────────────────────────────────────────

export const PLANTILLAS: Plantilla[] = [
  {
    id: 'vidriera',
    nombre: 'Vidriera',
    para: 'Indumentaria, accesorios, venta masiva',
    queCambia: 'La más usada en Argentina y la que más vende. Cartel de promo corriendo, logo centrado con buscador, carrusel a pantalla completa con la promo a 132 px, y las fotos pegadas entre sí ocupando todo el ancho. Es la única con la ficha de precio completa: transferencia, cuotas y swatches.',
    secciones: ['Cartel corriendo', 'Carrusel automático', 'Barra de confianza', 'Destacados a sangre', 'Categorías', 'Más vendidos', 'Cupón'],
    marca: 'Travesía', tagline: 'Anteojos de sol y de descanso',
    layout: 'tienda',
    // Header con el logo centrado + buscador en TODA la tienda (no solo el
    // home) — ver el comentario de este campo en tipos.ts.
    headerCentrado: true,
    cartel: '✦ 3X1 + ENVÍO GRATIS',
    links: ['Inicio', '3x1 en gafas', 'Lentes de sol', 'De descanso', 'Fotocromáticos'],
    confianza: [['Envío gratis', 'desde $80.000'], ['3 cuotas', 'sin interés'], ['Cambios', 'hasta 30 días'], ['Garantía', '1 año']],
    categorias: [['Lentes de sol', `${IMG}/vidriera-anteojos.jpg`], ['De descanso', `${IMG}/vidriera-reloj.jpg`], ['Zapatillas', `${IMG}/vidriera-zapatilla-roja.jpg`], ['Accesorios', `${IMG}/moda-zapato.jpg`]],
    cupon: { titulo: '15% extra en tu primera compra', bajada: 'Se aplica al pagar. No se acumula con otras promos.', codigo: 'TRAVESIA15' },
    pie: { columnas: [['Comprar', ['Lentes de sol', 'De descanso', '3x1']], ['Ayuda', ['Envíos', 'Cambios', 'Contacto']], ['Legales', ['Términos', 'Privacidad']]], cierre: 'Defensa al consumidor' },
    tema: {
      bg: '#FFFFFF', surf: '#FFFFFF', soft: '#F6F7F9', text: '#0F172A', muted: '#64748B', border: '#E6E9EE',
      primary: '#0F172A', onPrimary: '#FFFFFF', accent: '#2563EB',
      fh: sans('Poppins'), fb: sans('Poppins'), radio: 0, oscuro: false,
      sombra: '0 18px 40px -18px rgba(15,23,42,0.28)',
    },
    slides: [
      { img: `${IMG}/vidriera-modelo.jpg`, kicker: 'Definí tu estilo', titulo: '3x1', bajada: 'en lentes calidad óptica', cta: 'Ver el 3x1' },
      { img: `${IMG}/vidriera-local.jpg`, kicker: 'Nueva temporada', titulo: '−40%', bajada: 'en toda la línea de sol', cta: 'Ver ofertas' },
      { img: `${IMG}/vidriera-anteojos.jpg`, kicker: 'Envío gratis', titulo: '48 hs', bajada: 'a todo el país', cta: 'Comprar ahora' },
    ],
    productos: [
      { nombre: 'Wave', badge: 'Blue Light Cut', badgeTono: 'azul', tag: '3X1', estrellas: 5, resenas: 128, colores: ['#111827', '#B45309', '#64748B'], img: `${IMG}/vidriera-anteojos.jpg`, img2: `${IMG}/vidriera-modelo.jpg`, ...ar('$109.000', '$189.000', '$87.200', '$36.333') },
      { nombre: 'Lyra', badge: 'Fotocromático', badgeTono: 'verde', tag: '3X1', estrellas: 5, resenas: 74, stock: 'Quedan 3', colores: ['#0F172A', '#D97706'], img: `${IMG}/vidriera-reloj.jpg`, img2: `${IMG}/vidriera-local.jpg`, ...ar('$97.990', '$142.000', '$78.392', '$32.663') },
      { nombre: 'Specter', badge: 'Polarizado', badgeTono: 'violeta', tag: '3X1', estrellas: 4, resenas: 41, colores: ['#DC2626', '#111827', '#F1F5F9'], img: `${IMG}/vidriera-zapatilla-roja.jpg`, img2: `${IMG}/vidriera-zapatilla-blanca.jpg`, ...ar('$98.990', '$159.000', '$79.192', '$32.996') },
      { nombre: 'Pixel', badge: 'UV400', badgeTono: 'azul', tag: '3X1', estrellas: 5, resenas: 96, colores: ['#F1F5F9', '#EA580C'], img: `${IMG}/vidriera-zapatilla-blanca.jpg`, img2: `${IMG}/moda-zapato.jpg`, ...ar('$89.000', '$139.000', '$71.200', '$29.666') },
    ],
  },
  {
    id: 'escaparate',
    nombre: 'Escaparate',
    para: 'Indumentaria, calzado, moda urbana',
    queCambia: 'Arranca con DOS campañas a pantalla partida, cada una con su público y su botón — la forma más común de separar mujer/hombre o temporada/básicos. Después trae "Comprá el look": una foto grande con puntos numerados sobre las prendas y la lista al costado con precio y botón. Muy visual, muy de marca de ropa.',
    secciones: ['Doble campaña partida', 'Tira de lo nuevo', 'Comprá el look', 'Categorías', 'Envío gratis'],
    marca: 'Distrito', tagline: 'Ropa urbana, temporada tras temporada',
    layout: 'escaparate',
    tema: {
      bg: '#FFFFFF', surf: '#FFFFFF', soft: '#F4F4F5', text: '#09090B', muted: '#71717A', border: '#E4E4E7',
      primary: '#09090B', onPrimary: '#FFFFFF', accent: '#DC2626',
      fh: sans('Montserrat'), fb: sans('Inter'), radio: 4, oscuro: false,
      sombra: '0 20px 46px -22px rgba(9,9,11,0.36)',
    },
    slides: [
      { img: `${IMG}/moda-mujer-invierno.jpg`, kicker: 'Mujer', titulo: 'Abrigos\nque abrigan', bajada: 'Nueva temporada', cta: 'Ver mujer' },
    ],
    productos: [
      { nombre: 'Campera puffer', badge: 'Nuevo', badgeTono: 'verde', estrellas: 5, resenas: 62, colores: ['#09090B', '#DC2626', '#D4D4D8'], img: `${IMG}/moda-mujer-invierno.jpg`, img2: `${IMG}/vidriera-modelo.jpg`, ...ar('$142.000', '$189.000', '$113.600', '$47.333') },
      { nombre: 'Zapatilla urbana', badge: 'Últimos talles', badgeTono: 'rojo', estrellas: 5, resenas: 148, colores: ['#DC2626', '#FFFFFF'], img: `${IMG}/vidriera-zapatilla-roja.jpg`, img2: `${IMG}/vidriera-zapatilla-blanca.jpg`, ...ar('$118.000', '$156.000', '$94.400', '$39.333') },
      { nombre: 'Zapato de cuero', estrellas: 4, resenas: 33, colores: ['#0F766E', '#78350F'], img: `${IMG}/moda-zapato.jpg`, img2: `${IMG}/vidriera-local.jpg`, ...ar('$186.000', '$232.000', '$148.800', '$62.000') },
      { nombre: 'Runner blanca', badge: 'Best seller', badgeTono: 'violeta', estrellas: 5, resenas: 211, colores: ['#FFFFFF', '#EA580C'], img: `${IMG}/vidriera-zapatilla-blanca.jpg`, img2: `${IMG}/vidriera-zapatilla-roja.jpg`, ...ar('$134.000', '$168.000', '$107.200', '$44.666') },
    ],
  },
  {
    id: 'mosaico',
    nombre: 'Mosaico',
    para: 'Casa, deco, tiendas con muchas categorías',
    queCambia: 'La única sin hero: arranca con un muro de bloques de distinta altura, uno grande de campaña y cuatro de categoría con su porcentaje. Los productos van compactos, cinco por fila, con lo justo. Sirve cuando vendés cosas variadas y no hay UNA sola para destacar.',
    secciones: ['Sin hero', 'Muro de bloques', 'Grilla compacta de 5', 'Franja de envío', 'Marcas'],
    marca: 'Mercado Sur', tagline: 'Casa, cocina y jardín',
    layout: 'mosaico',
    tema: {
      bg: '#FAFAF9', surf: '#FFFFFF', soft: '#F1F1EF', text: '#1C1917', muted: '#78716C', border: '#E4E4E1',
      primary: '#0D9488', onPrimary: '#FFFFFF', accent: '#F59E0B',
      fh: sans('Montserrat'), fb: sans('Inter'), radio: 16, oscuro: false,
      sombra: '0 16px 38px -20px rgba(28,25,23,0.30)',
    },
    slides: [
      { img: `${IMG}/casa-living.jpg`, kicker: 'Temporada', titulo: 'Todo para\nrenovar la casa', bajada: 'Hasta 40% en cocina, textil y jardín.', cta: 'Ver ofertas' },
    ],
    productos: [
      { nombre: 'Set de cerámica esmaltada', badge: 'Envío gratis', badgeTono: 'verde', estrellas: 5, resenas: 62, colores: ['#D6D3D1', '#78716C'], img: `${IMG}/casa-ceramica.jpg`, img2: `${IMG}/casa-deco.jpg`, ...ar('$142.000', '$198.000', '$113.600', '$47.333') },
      { nombre: 'Sillón Nórdico crema', estrellas: 4, resenas: 18, colores: ['#F5F5F4', '#292524'], img: `${IMG}/casa-sillon.jpg`, img2: `${IMG}/casa-sofa-naranja.jpg`, ...ar('$486.900', '$620.000', '$389.520', '$162.300') },
      { nombre: 'Planta de interior + maceta', badge: 'Últimas 4', badgeTono: 'rojo', estrellas: 5, resenas: 31, stock: 'Quedan 4', img: `${IMG}/casa-plantas.jpg`, img2: `${IMG}/casa-deco.jpg`, ...ar('$28.500', '$38.000', '$22.800', '$9.500') },
      { nombre: 'Sofá de tres cuerpos', estrellas: 5, resenas: 47, colores: ['#EA580C', '#1C1917', '#D6D3D1'], img: `${IMG}/casa-sofa-naranja.jpg`, img2: `${IMG}/casa-living-2.jpg`, ...ar('$880.000', '$1.150.000', '$704.000', '$293.333') },
    ],
  },
  {
    id: 'premium',
    nombre: 'Premium',
    para: 'Joyería, relojería, accesorios de alta gama',
    queCambia: 'Fondo carbón con dorado y mucho aire alrededor de cada pieza. El producto se presenta de a una, grande y con foco, no en grilla apretada. Precios en dorado, sin tachados ni carteles de oferta: acá el argumento es la pieza, no el descuento.',
    secciones: ['Header dorado', 'Hero con foco sobre negro', 'Categorías oscuras', 'Piezas de a tres', 'Certificaciones', 'Grabado personalizado'],
    marca: 'Solano', tagline: 'Joyería en oro 18k, hecha a pedido',
    layout: 'premium',
    tema: {
      bg: '#0C0A09', surf: '#171412', soft: '#12100E', text: '#F5F1EA', muted: '#A8A29E', border: '#2A2521',
      primary: '#C9A227', onPrimary: '#1C1917', accent: '#E0C060',
      fh: serif('Cormorant Garamond'), fb: sans('Lato'), radio: 2, oscuro: true,
      sombra: '0 24px 60px -28px rgba(201,162,39,0.35)',
    },
    slides: [
      { img: `${IMG}/joya-pulsera.jpg`, kicker: 'Colección Aurora', titulo: 'Piezas que\nse heredan', bajada: 'Oro 18k y piedras seleccionadas a mano. Cada pieza sale con su certificado.', cta: 'Ver la colección' },
    ],
    productos: [
      { nombre: 'Anillo Aurora · oro 18k', precio: '$1.240.000', badge: 'Hecho a pedido', badgeTono: 'verde', estrellas: 5, resenas: 46, img: `${IMG}/joya-anillo.jpg`, img2: `${IMG}/joya-anillos-caja.jpg` },
      { nombre: 'Cadena Aurora · oro 18k', precio: '$1.680.000', badge: 'Única', badgeTono: 'violeta', estrellas: 5, resenas: 12, img: `${IMG}/joya-cadena.jpg`, img2: `${IMG}/joya-pulsera.jpg` },
      { nombre: 'Aros Duna · oro y turquesa', precio: '$980.000', estrellas: 5, resenas: 31, img: `${IMG}/joya-set.jpg`, img2: `${IMG}/joya-pulsera-rosa.jpg` },
      { nombre: 'Reloj automático acero', precio: '$2.150.000', estrellas: 5, resenas: 58, img: `${IMG}/joya-reloj.jpg`, img2: `${IMG}/joya-pulsera.jpg` },
    ],
  },
  {
    id: 'nocturno',
    nombre: 'Nocturno',
    para: 'Gaming, audio, componentes',
    queCambia: 'Oscura y con datos en vez de frases. Barra de lanzamiento con contador, el producto flotando sobre un foco de luz, categorías con su cantidad de artículos, carrusel horizontal con specs adentro de cada tarjeta, armador de setup en tres pasos y comparativa de tres modelos.',
    secciones: ['Contador de lanzamiento', 'Hero con foco de luz', 'Categorías', 'Carrusel con specs', 'Armá tu setup', 'Comparativa', 'Números grandes'],
    marca: 'Vector', tagline: 'Periféricos y audio, sin vueltas',
    layout: 'nocturno',
    tema: {
      bg: '#0B1120', surf: '#131C2E', soft: '#101827', text: '#F1F5F9', muted: '#94A3B8', border: '#1E293B',
      primary: '#22D3EE', onPrimary: '#04121A', accent: '#818CF8',
      fh: sans('Geist'), fb: sans('Geist'), radio: 10, oscuro: true,
      sombra: '0 22px 50px -26px rgba(34,211,238,0.45)',
    },
    slides: [
      { img: `${IMG}/tech-auriculares.jpg`, kicker: 'Nuevo · V-90 Pro', titulo: 'Auriculares\nV-90 Pro', bajada: 'Driver de 50 mm, 38 horas de batería y cancelación activa de 35 dB.', cta: 'Ver ficha completa' },
    ],
    productos: [
      { nombre: 'Teclado 75% hot-swap', badge: 'Switch lineal', badgeTono: 'azul', estrellas: 5, resenas: 143, colores: ['#111827', '#F1F5F9'], img: `${IMG}/tech-teclado-2.jpg`, img2: `${IMG}/tech-teclado.jpg`, ...ar('$189.000', '$229.000', '$151.200', '$63.000') },
      { nombre: 'Mouse inalámbrico 8K', badge: '54 g', badgeTono: 'violeta', estrellas: 4, resenas: 88, img: `${IMG}/tech-mouse.jpg`, img2: `${IMG}/tech-setup.jpg`, ...ar('$142.000', '$168.000', '$113.600', '$47.333') },
      { nombre: 'Auriculares over-ear', badge: 'ANC 35 dB', badgeTono: 'verde', estrellas: 5, resenas: 211, stock: 'Quedan 2', img: `${IMG}/tech-auriculares-2.jpg`, img2: `${IMG}/tech-auriculares.jpg`, ...ar('$249.000', '$310.000', '$199.200', '$83.000') },
      { nombre: 'Setup completo gamer', badge: 'Combo', badgeTono: 'rojo', estrellas: 5, resenas: 37, img: `${IMG}/tech-setup.jpg`, img2: `${IMG}/tech-notebook.jpg`, ...ar('$1.240.000', '$1.520.000', '$992.000', '$413.333') },
    ],
  },
  {
    id: 'glow',
    nombre: 'Glow',
    para: 'Cosmética, skincare, perfumería',
    queCambia: 'Rosa y nude con degradés suaves, pero vendedora: la rutina se muestra con los tres productos numerados y su precio, no con párrafos. Trae grilla de best sellers con estrellas, un antes y después, y una galería de Instagram al pie. Bonita sin dejar de ser tienda.',
    secciones: ['Hero con degradé', 'Sellos de producto', 'Rutina en 3 productos', 'Best sellers', 'Antes y después', 'Galería de Instagram'],
    marca: 'Aura', tagline: 'Skincare simple, resultados visibles',
    layout: 'glow',
    tema: {
      bg: '#FFF9FB', surf: '#FFFFFF', soft: '#FDEEF3', text: '#3B1027', muted: '#9B6B80', border: '#F6DCE6',
      primary: '#DB2777', onPrimary: '#FFFFFF', accent: '#C084FC',
      fh: sans('Poppins'), fb: sans('Lato'), radio: 22, oscuro: false,
      sombra: '0 20px 46px -22px rgba(219,39,119,0.30)',
    },
    slides: [
      { img: `${IMG}/belleza-labial.jpg`, kicker: 'Nueva línea', titulo: 'Tu piel,\nsin filtros', bajada: 'Fórmulas cortas, activos en la dosis que sirve.', cta: 'Ver la línea' },
    ],
    productos: [
      { nombre: 'Sérum de vitamina C', badge: 'Best seller', badgeTono: 'violeta', estrellas: 5, resenas: 428, precio: '$34.000', antes: '$42.000', img: `${IMG}/belleza-cosmetica.jpg`, img2: `${IMG}/relato-cosmetica.jpg` },
      { nombre: 'Paleta de sombras', badge: '12 tonos', badgeTono: 'violeta', estrellas: 5, resenas: 216, precio: '$28.500', colores: ['#B45309', '#DB2777', '#7C3AED'], img: `${IMG}/belleza-paletas.jpg`, img2: `${IMG}/belleza-paleta-2.jpg` },
      { nombre: 'Labial hidratante', badge: 'Vegano', badgeTono: 'verde', estrellas: 5, resenas: 519, precio: '$14.900', colores: ['#DC2626', '#DB2777', '#9F1239'], img: `${IMG}/belleza-coral.jpg`, img2: `${IMG}/belleza-maquillaje.jpg` },
      { nombre: 'Crema de noche', badge: 'Piel sensible', badgeTono: 'azul', estrellas: 4, resenas: 137, precio: '$26.000', img: `${IMG}/relato-cosmetica.jpg`, img2: `${IMG}/belleza-cosmetica.jpg` },
    ],
  },
  {
    id: 'papeleria',
    nombre: 'Papelería',
    para: 'Librería, papelería, arte, insumos de oficina',
    queCambia: 'La única que arranca con el buscador como protagonista: en una librería nadie navega, viene a buscar algo puntual. Hero con un campo grande y búsquedas frecuentes, categorías en pastillas y un armador de lista escolar con casilleros y total, que ninguna otra tiene.',
    secciones: ['Buscador protagonista', 'Búsquedas frecuentes', 'Categorías en pastillas', 'Armá tu lista escolar', 'Grilla de 4', 'Vuelta a clases'],
    marca: 'Renglón', tagline: 'Librería, papelería y arte',
    layout: 'papeleria',
    tema: {
      bg: '#FAF7F0', surf: '#FFFFFF', soft: '#F3EEE3', text: '#1C1917', muted: '#78716C', border: '#E7E0D2',
      primary: '#1D4ED8', onPrimary: '#FFFFFF', accent: '#F59E0B',
      fh: sans('Poppins'), fb: sans('Inter'), radio: 12, oscuro: false,
      sombra: '0 16px 34px -20px rgba(29,78,216,0.35)',
    },
    slides: [
      { img: `${IMG}/libre-escolar.jpg`, kicker: 'Vuelta a clases', titulo: '¿Qué necesitás?', bajada: 'Más de 4.000 artículos de librería, papelería y arte. Buscá por nombre, marca o código.', cta: 'Buscar' },
    ],
    productos: [
      { nombre: 'Cuaderno tapa dura A4', badge: 'Más vendido', badgeTono: 'azul', estrellas: 5, resenas: 214, colores: ['#1E3A8A', '#B91C1C', '#065F46'], img: `${IMG}/libre-cuaderno.jpg`, img2: `${IMG}/libre-anotador.jpg`, ...ar('$4.900', '$6.200', '$3.920', '$1.633') },
      { nombre: 'Set 24 lápices de colores', badge: 'Escolar', badgeTono: 'verde', estrellas: 5, resenas: 168, img: `${IMG}/libre-lapices.jpg`, img2: `${IMG}/libre-escolar.jpg`, ...ar('$8.700', '$11.000', '$6.960', '$2.900') },
      { nombre: 'Mochila reforzada 18"', estrellas: 4, resenas: 92, stock: 'Quedan 6', colores: ['#1F2937', '#0F766E'], img: `${IMG}/libre-mochila.jpg`, img2: `${IMG}/libre-escolar.jpg`, ...ar('$38.500', '$48.000', '$30.800', '$12.833') },
      { nombre: 'Lapicera roller punta fina', badge: 'Oficina', badgeTono: 'violeta', estrellas: 5, resenas: 341, img: `${IMG}/libre-lapicera.jpg`, img2: `${IMG}/libre-cuaderno.jpg`, ...ar('$2.400', '$3.100', '$1.920', '$800') },
    ],
  },
  {
    id: 'corralon',
    nombre: 'Corralón',
    para: 'Ferretería, corralón, materiales, pinturería',
    queCambia: 'Pensada para catálogos enormes: barra de doce departamentos siempre visible, hero partido en tres avisos operativos (retiro, envío, cuenta corriente) y fichas de producto con tabla de especificaciones. Trae una calculadora de materiales que ninguna otra plantilla tiene.',
    secciones: ['Barra de departamentos', 'Hero partido en tres', 'Calculadora de materiales', 'Fichas con especificaciones', 'Retiro en sucursal'],
    marca: 'Bulón', tagline: 'Ferretería y corralón desde 1972',
    layout: 'corralon',
    tema: {
      bg: '#FFFFFF', surf: '#FFFFFF', soft: '#F5F5F4', text: '#0C0A09', muted: '#57534E', border: '#D6D3D1',
      primary: '#111827', onPrimary: '#FACC15', accent: '#FACC15',
      fh: sans('Montserrat'), fb: sans('Inter'), radio: 4, oscuro: false,
      sombra: '0 14px 30px -18px rgba(12,10,9,0.45)',
    },
    slides: [
      { img: `${IMG}/ferre-corralon.jpg`, kicker: 'Retirá hoy', titulo: 'Todo para la obra\ny el arreglo', bajada: 'Nueve sucursales con stock propio. Comprás online y retirás en el día.', cta: 'Ver departamentos' },
    ],
    productos: [
      { nombre: 'Taladro percutor 750W', badge: 'Envío gratis', badgeTono: 'verde', estrellas: 5, resenas: 128, tag: '13 mm · 2.900 rpm · 2 velocidades', img: `${IMG}/ferre-taladro.jpg`, img2: `${IMG}/ferre-taladro-rojo.jpg`, ...ar('$132.000', '$168.000', '$105.600', '$44.000') },
      { nombre: 'Juego de formones 6 piezas', estrellas: 5, resenas: 64, tag: 'Acero al cromo · 6 a 32 mm · estuche', img: `${IMG}/ferre-formones.jpg`, img2: `${IMG}/ferre-pared.jpg`, ...ar('$46.800', '$59.000', '$37.440', '$15.600') },
      { nombre: 'Látex interior 20 L', badge: 'Más vendido', badgeTono: 'azul', estrellas: 4, resenas: 203, tag: 'Rinde 12 m² por litro · lavable · blanco', img: `${IMG}/ferre-pintura.jpg`, img2: `${IMG}/ferre-cocina.jpg`, ...ar('$89.900', '$112.000', '$71.920', '$29.966') },
      { nombre: 'Amoladora angular 4½"', estrellas: 4, resenas: 87, stock: 'Últimas 3', tag: '900W · 11.000 rpm · con disco', img: `${IMG}/ferre-electronica.jpg`, img2: `${IMG}/ferre-canos.jpg`, ...ar('$74.500', '$95.000', '$59.600', '$24.833') },
    ],
  },
  {
    id: 'atleta',
    nombre: 'Atleta',
    para: 'Running, entrenamiento, ciclismo, indumentaria deportiva',
    queCambia: 'Negro y lima, tipografía condensada en mayúsculas y foto a sangre de borde a borde. El catálogo no se muestra en grilla sino en tiras horizontales por disciplina que se arrastran con el dedo, y cierra con los números de la comunidad. Es la más agresiva de las doce.',
    secciones: ['Hero a sangre', 'Tiras por disciplina', 'Fichas con tecnología', 'Números de la comunidad', 'Guía de talles'],
    marca: 'Ritmo', tagline: 'Running, fuerza y ciclismo',
    layout: 'atleta',
    tema: {
      bg: '#0A0A0A', surf: '#141414', soft: '#171717', text: '#FAFAFA', muted: '#A3A3A3', border: '#262626',
      primary: '#BEF264', onPrimary: '#0A0A0A', accent: '#F97316',
      fh: sans('Oswald'), fb: sans('Inter'), radio: 3, oscuro: true,
      sombra: '0 20px 44px -22px rgba(190,242,100,0.35)',
    },
    slides: [
      { img: `${IMG}/dep-correr.jpg`, kicker: 'Temporada 26', titulo: 'NO EMPIEZA\nMAÑANA', bajada: 'Zapatillas, indumentaria técnica y accesorios para entrenar todos los días del año.', cta: 'Ver la colección' },
    ],
    productos: [
      { nombre: 'Zapatilla de running Vento', badge: 'Nueva', badgeTono: 'verde', estrellas: 5, resenas: 176, tag: 'Amortiguación de 32 mm · 218 g', colores: ['#DC2626', '#171717', '#BEF264'], img: `${IMG}/dep-zapatilla-roja.jpg`, img2: `${IMG}/dep-zapatilla.jpg`, ...ar('$189.000', '$240.000', '$151.200', '$63.000') },
      { nombre: 'Calza técnica compresión', estrellas: 5, resenas: 214, tag: 'Tejido de secado rápido · bolsillo lateral', colores: ['#171717', '#525252'], img: `${IMG}/dep-estirar.jpg`, img2: `${IMG}/dep-abdominales.jpg`, ...ar('$62.000', '$78.000', '$49.600', '$20.666') },
      { nombre: 'Bicicleta urbana fija', badge: 'Últimas 2', badgeTono: 'rojo', estrellas: 5, resenas: 41, stock: 'Quedan 2', tag: 'Cuadro de acero · rodado 28', img: `${IMG}/dep-bici.jpg`, img2: `${IMG}/dep-pista.jpg`, ...ar('$540.000', '$690.000', '$432.000', '$180.000') },
      { nombre: 'Set de mancuernas 2 × 10 kg', estrellas: 4, resenas: 98, tag: 'Recubiertas en goma · agarre moleteado', img: `${IMG}/dep-pesas.jpg`, img2: `${IMG}/dep-sentadilla.jpg`, ...ar('$118.000', '$149.000', '$94.400', '$39.333') },
    ],
  },
  {
    id: 'patitas',
    nombre: 'Patitas',
    para: 'Pet shop, alimento, accesorios, veterinaria',
    queCambia: 'Crema y coral, todo redondeado, con las fotos en círculo. Arranca preguntando para quién comprás y ofrece tres círculos grandes (perro, gato, otros) en vez de un menú de categorías: es como se compra en un pet shop, pensando en el animal y no en el rubro.',
    secciones: ['¿Para quién comprás?', 'Hero redondeado', 'Fichas con badge', 'Categorías en círculo'],
    marca: 'Colita', tagline: 'Todo para tu perro y tu gato',
    layout: 'patitas',
    tema: {
      bg: '#FFF9F5', surf: '#FFFFFF', soft: '#FFF0E6', text: '#2D1B12', muted: '#8B7268', border: '#F2DFD1',
      primary: '#F97316', onPrimary: '#FFFFFF', accent: '#22C55E',
      fh: sans('Nunito'), fb: sans('Nunito'), radio: 20, oscuro: false,
      sombra: '0 20px 40px -22px rgba(249,115,22,0.4)',
    },
    slides: [
      { img: `${IMG}/masc-perro-rosa.jpg`, kicker: 'Envío en el día', titulo: 'Lo mejor\npara tu compañero', bajada: 'Alimento, juguetes, camas y accesorios elegidos por veterinarios. Llega hoy si comprás antes de las 14.', cta: 'Empezar a comprar' },
    ],
    productos: [
      { nombre: 'Alimento premium perro adulto 15 kg', badge: 'Más vendido', badgeTono: 'verde', estrellas: 5, resenas: 312, img: `${IMG}/masc-entrega.jpg`, img2: `${IMG}/masc-perro.jpg`, ...ar('$74.900', '$92.000', '$59.920', '$24.966') },
      { nombre: 'Cama redonda desenfundable', estrellas: 5, resenas: 147, colores: ['#F97316', '#78716C', '#22C55E'], img: `${IMG}/masc-collie.jpg`, img2: `${IMG}/masc-perros.jpg`, ...ar('$56.000', '$71.000', '$44.800', '$18.666') },
      { nombre: 'Rascador de sisal con plataforma', badge: 'Gatos', badgeTono: 'violeta', estrellas: 5, resenas: 89, img: `${IMG}/masc-gato.jpg`, img2: `${IMG}/masc-gato-naranja.jpg`, ...ar('$42.300', '$54.000', '$33.840', '$14.100') },
      { nombre: 'Kit de juguetes mordillo', estrellas: 4, resenas: 205, stock: 'Quedan 8', img: `${IMG}/masc-bulldog.jpg`, img2: `${IMG}/masc-pug.jpg`, ...ar('$18.900', '$24.000', '$15.120', '$6.300') },
    ],
  },
  {
    id: 'bodega',
    nombre: 'Bodega',
    para: 'Vinotecas, bebidas, bodegas, delicatessen',
    queCambia: 'Borgoña y terracota. La sección central no tiene una sola foto: es una lista tipográfica de varietales, como la carta de un restaurante. Las botellas se muestran altas y angostas sobre tarjetas color crema que recortan contra el fondo oscuro, y cierra con maridajes.',
    secciones: ['Índice editorial', 'Lista de varietales sin fotos', 'Botellas altas sobre crema', 'Maridajes'],
    marca: 'Cepa', tagline: 'Vinos de autor y bodegas chicas',
    layout: 'bodega',
    tema: {
      bg: '#1A0F12', surf: '#241419', soft: '#201216', text: '#F5EDE6', muted: '#A99188', border: '#3A2228',
      primary: '#D4A373', onPrimary: '#1A0F12', accent: '#9F1239',
      fh: serif('Cormorant Garamond'), fb: sans('Lato'), radio: 0, oscuro: true,
      sombra: '0 24px 52px -26px rgba(212,163,115,0.35)',
    },
    slides: [
      { img: `${IMG}/vino-uvas.jpg`, kicker: 'Selección de octubre', titulo: 'Doce bodegas\nque no vas a\nencontrar en el súper', bajada: 'Producciones cortas del Valle de Uco, Salta y la Patagonia. Cada etiqueta con su ficha de cata.', cta: 'Ver la selección' },
    ],
    productos: [
      { nombre: 'Malbec de altura 2021', precio: '$28.400', estrellas: 5, resenas: 64, tag: 'Valle de Uco · 1.100 msnm', img: `${IMG}/vino-botella.jpg`, img2: `${IMG}/vino-oscuro.jpg` },
      { nombre: 'Cabernet Franc 2020', precio: '$34.900', badge: 'Últimas 6', badgeTono: 'rojo', estrellas: 5, resenas: 38, tag: 'Agrelo · guarda 12 meses', img: `${IMG}/vino-estante.jpg`, img2: `${IMG}/vino-servir-copa.jpg` },
      { nombre: 'Pinot Noir patagónico 2022', precio: '$41.200', estrellas: 5, resenas: 27, tag: 'Río Negro · producción de 3.000 botellas', img: `${IMG}/vino-oscuro.jpg`, img2: `${IMG}/vino-botella.jpg` },
      { nombre: 'Espumante método tradicional', precio: '$24.800', estrellas: 4, resenas: 51, tag: '18 meses sobre lías', img: `${IMG}/vino-brindis.jpg`, img2: `${IMG}/vino-copas-luz.jpg` },
    ],
  },
  {
    id: 'crecer',
    nombre: 'Crecer',
    para: 'Bebés, primera infancia, juguetería, ropa infantil',
    queCambia: 'Pastel, muy redondeada y con mucho aire. No se navega por categoría sino por EDAD, en una línea de tiempo horizontal con puntos (0-6 m, 6-12 m, 1-2 años…), porque es como compra el que regala: sabe los meses que tiene, no el rubro que busca.',
    secciones: ['Línea de tiempo por edad', 'Hero suave', 'Certificaciones'],
    marca: 'Nube', tagline: 'Para los primeros años',
    layout: 'crecer',
    tema: {
      bg: '#FFFDFB', surf: '#FFFFFF', soft: '#F4F7FA', text: '#33302E', muted: '#8A8580', border: '#EAE6E1',
      primary: '#7FA9C9', onPrimary: '#FFFFFF', accent: '#F0B49B',
      fh: sans('Quicksand'), fb: sans('Quicksand'), radio: 24, oscuro: false,
      sombra: '0 22px 44px -24px rgba(127,169,201,0.45)',
    },
    slides: [
      { img: `${IMG}/bebe-oso.jpg`, kicker: 'Otoño invierno', titulo: 'Suave desde\nel primer día', bajada: 'Algodón orgánico certificado, sin tinturas agresivas y con costuras planas. Pensado para pieles que recién empiezan.', cta: 'Ver por edad' },
    ],
    productos: [
      { nombre: 'Enterito de algodón orgánico', badge: 'Orgánico', badgeTono: 'verde', estrellas: 5, resenas: 186, colores: ['#F0B49B', '#7FA9C9', '#E8E4DF'], img: `${IMG}/bebe-oso.jpg`, img2: `${IMG}/bebe-ropa.jpg`, ...ar('$24.900', '$31.000', '$19.920', '$8.300') },
      { nombre: 'Tren de madera 24 piezas', badge: 'Sin tóxicos', badgeTono: 'azul', estrellas: 5, resenas: 94, img: `${IMG}/bebe-tren.jpg`, img2: `${IMG}/bebe-juguetes.jpg`, ...ar('$38.500', '$47.000', '$30.800', '$12.833') },
      { nombre: 'Manta de algodón con capucha', estrellas: 5, resenas: 132, colores: ['#F4F7FA', '#F0B49B'], img: `${IMG}/bebe-pies.jpg`, img2: `${IMG}/bebe-verano.jpg`, ...ar('$29.700', '$36.000', '$23.760', '$9.900') },
      { nombre: 'Set de primeros juguetes', estrellas: 4, resenas: 78, stock: 'Quedan 5', img: `${IMG}/bebe-juguetes.jpg`, img2: `${IMG}/bebe-nena.jpg`, ...ar('$21.400', '$27.000', '$17.120', '$7.133') },
    ],
  },
  {
    id: 'semilla',
    nombre: 'Semilla',
    para: 'Dietética, almacén natural, venta a granel',
    queCambia: 'Verde oliva sobre papel crema con Fraunces serif y esquinas suaves. Categorías por tipo de producto seco (frutos secos, legumbres, especias, almacén) y barra de confianza con granel desde 100 g y retiro en el local.',
    secciones: ['Cartel corriendo', 'Carrusel', 'Barra de confianza', 'Destacados', 'Categorías', 'Más vendidos', 'Cupón'],
    marca: 'Semilla', tagline: 'Dietética, granel y almacén natural',
    layout: 'tienda',
    cartel: '✦ GRANEL DESDE 100 G ✦ ENVÍO GRATIS SUPERANDO $35.000',
    links: ['Inicio', 'Granel', 'Frutos secos', 'Legumbres', 'Almacén'],
    confianza: [['Envío gratis', 'desde $35.000'], ['Granel', 'desde 100 g'], ['Retiro', 'en el local'], ['Sin TACC', 'identificado']],
    categorias: [['Frutos secos', `${IMG}/diet-frutos-secos.jpg`], ['Legumbres', `${IMG}/diet-legumbres.jpg`], ['Especias', `${IMG}/diet-tarros.jpg`], ['Almacén', `${IMG}/diet-estante.jpg`]],
    cupon: { titulo: '10% llevando 2 kg o más', bajada: 'Se aplica al pagar. No se acumula con otras promos.', codigo: 'SEMILLA10' },
    pie: { columnas: [['Comprar', ['Granel', 'Frutos secos', 'Legumbres', 'Almacén']], ['Ayuda', ['Envíos', 'Cambios', 'Contacto']], ['Legales', ['Términos', 'Privacidad']]], cierre: 'Local en Villa Crespo' },
    tema: {
      bg: '#FBF9F4', surf: '#FFFFFF', soft: '#F2EFE6', text: '#23291F', muted: '#6E7566', border: '#E4E0D3',
      primary: '#4D6B3C', onPrimary: '#FFFFFF', accent: '#C2703D',
      fh: serif('Fraunces'), fb: sans('Inter'), radio: 14, oscuro: false,
      sombra: '0 18px 38px -20px rgba(77,107,60,0.35)',
    },
    slides: [
      { img: `${IMG}/diet-granel.jpg`, kicker: 'Todo por peso', titulo: '−25%', bajada: 'en granel llevando 2 kg', cta: 'Ver el granel' },
      { img: `${IMG}/diet-cestas.jpg`, kicker: 'Frutos secos', titulo: '3x2', bajada: 'en almendras y nueces', cta: 'Ver el 3x2' },
      { img: `${IMG}/diet-local.jpg`, kicker: 'Envío gratis', titulo: '48 hs', bajada: 'desde $35.000', cta: 'Comprar ahora' },
    ],
    productos: [
      { nombre: 'Almendras tostadas · 500 g', badge: 'Más vendido', badgeTono: 'verde', estrellas: 5, resenas: 186, img: `${IMG}/diet-almendras.jpg`, img2: `${IMG}/diet-frutos-secos.jpg`, ...ar('$12.900', '$16.500', '$10.320', '$4.300') },
      { nombre: 'Mix de nueces y castañas · 1 kg', estrellas: 5, resenas: 94, stock: 'Quedan 7', img: `${IMG}/diet-nueces.jpg`, img2: `${IMG}/diet-semillas.jpg`, ...ar('$28.400', '$35.000', '$22.720', '$9.466') },
      { nombre: 'Lentejas turcas · 1 kg', badge: 'A granel', badgeTono: 'azul', estrellas: 4, resenas: 122, img: `${IMG}/diet-legumbres.jpg`, img2: `${IMG}/diet-cestas.jpg`, ...ar('$6.900', '$8.900', '$5.520', '$2.300') },
      { nombre: 'Páprika dulce ahumada · 250 g', badge: 'Sin agregados', badgeTono: 'violeta', estrellas: 5, resenas: 63, img: `${IMG}/diet-paprika.jpg`, img2: `${IMG}/diet-tarros.jpg`, ...ar('$4.800', '$6.200', '$3.840', '$1.600') },
    ],
  },
  {
    id: 'lunar',
    nombre: 'Lunar',
    para: 'Indumentaria de mujer, boutique, showroom',
    queCambia: 'Arena y negro tinta con Playfair Display serif y esquinas rectas, el código de una boutique chica. Categorías por prenda (vestidos, camisas, pantalones) y barra de confianza con cambios sin cargo y retiro en el showroom.',
    secciones: ['Cartel corriendo', 'Carrusel', 'Barra de confianza', 'Destacados', 'Categorías', 'Más vendidos', 'Cupón'],
    marca: 'Lunar', tagline: 'Ropa de mujer, temporada corta',
    layout: 'tienda',
    cartel: '✦ ENVÍO GRATIS DESDE $90.000 ✦ CAMBIOS SIN CARGO 30 DÍAS',
    links: ['Inicio', 'Vestidos', 'Camisas', 'Pantalones', 'Nueva temporada'],
    confianza: [['Envío gratis', 'desde $90.000'], ['Cambios', 'sin cargo'], ['3 cuotas', 'sin interés'], ['Retiro', 'en el showroom']],
    categorias: [['Vestidos', `${IMG}/boutique-vestido-blanco.jpg`], ['Camisas', `${IMG}/boutique-camisas.jpg`], ['Pantalones', `${IMG}/boutique-pantalones.jpg`], ['Nueva temporada', `${IMG}/boutique-perchero.jpg`]],
    cupon: { titulo: '15% en tu primera compra', bajada: 'Se aplica al pagar. No se acumula con otras promos.', codigo: 'LUNAR15' },
    pie: { columnas: [['Comprar', ['Vestidos', 'Camisas', 'Pantalones']], ['Ayuda', ['Guía de talles', 'Cambios', 'Envíos']], ['Legales', ['Términos', 'Privacidad']]], cierre: 'Showroom en Palermo, con cita' },
    tema: {
      bg: '#FFFFFF', surf: '#FFFFFF', soft: '#F7F4EF', text: '#1A1614', muted: '#7A716A', border: '#E8E2D9',
      primary: '#1A1614', onPrimary: '#FFFFFF', accent: '#B4784F',
      fh: serif('Playfair Display'), fb: sans('Inter'), radio: 0, oscuro: false,
      sombra: '0 20px 44px -22px rgba(26,22,20,0.32)',
    },
    slides: [
      { img: `${IMG}/boutique-modelo.jpg`, kicker: 'Temporada 26', titulo: '−30%', bajada: 'en la colección de verano', cta: 'Ver la colección' },
      { img: `${IMG}/boutique-local.jpg`, kicker: 'Nuevo ingreso', titulo: '2x1', bajada: 'en camisas de lino', cta: 'Ver camisas' },
      { img: `${IMG}/boutique-vidriera.jpg`, kicker: 'Envío gratis', titulo: '48 hs', bajada: 'desde $90.000', cta: 'Comprar ahora' },
    ],
    productos: [
      { nombre: 'Vestido largo de lino', badge: 'Nuevo', badgeTono: 'verde', estrellas: 5, resenas: 74, colores: ['#F2EDE4', '#B4784F', '#1A1614'], img: `${IMG}/boutique-vestido-blanco.jpg`, img2: `${IMG}/boutique-perchero.jpg`, ...ar('$148.000', '$189.000', '$118.400', '$49.333') },
      { nombre: 'Camisa oversize de algodón', estrellas: 5, resenas: 138, colores: ['#FFFFFF', '#D8CFC2'], img: `${IMG}/boutique-camisas.jpg`, img2: `${IMG}/boutique-beige.jpg`, ...ar('$86.000', '$109.000', '$68.800', '$28.666') },
      { nombre: 'Pantalón sastrero de tiro alto', badge: 'Últimos talles', badgeTono: 'rojo', estrellas: 4, resenas: 46, stock: 'Quedan 4', colores: ['#E4DACB', '#1A1614'], img: `${IMG}/boutique-pantalones.jpg`, img2: `${IMG}/boutique-probador.jpg`, ...ar('$112.000', '$142.000', '$89.600', '$37.333') },
      { nombre: 'Vestido midi verde', badge: 'Best seller', badgeTono: 'violeta', estrellas: 5, resenas: 91, colores: ['#4A5D43', '#1A1614'], img: `${IMG}/boutique-vestido-verde.jpg`, img2: `${IMG}/boutique-local.jpg`, ...ar('$134.000', '$168.000', '$107.200', '$44.666') },
    ],
  },
  {
    id: 'tueste',
    nombre: 'Tueste',
    para: 'Café de especialidad, tostaduría, té e infusiones',
    queCambia: 'Espresso y crema con DM Serif Display y un verde de acento. Categorías por formato (en grano, molido, blends, accesorios) y barra de confianza con tostado a pedido y retiro en la tostaduría.',
    secciones: ['Cartel corriendo', 'Carrusel', 'Barra de confianza', 'Destacados', 'Categorías', 'Más vendidos', 'Cupón'],
    marca: 'Tueste', tagline: 'Café de especialidad, tostado acá',
    layout: 'tienda',
    cartel: '✦ TOSTAMOS MARTES Y JUEVES ✦ ENVÍO GRATIS DESDE $30.000',
    links: ['Inicio', 'En grano', 'Molido', 'Blends', 'Accesorios'],
    confianza: [['Tostado', 'a pedido'], ['Envío gratis', 'desde $30.000'], ['3 cuotas', 'sin interés'], ['Retiro', 'en la tostaduría']],
    categorias: [['En grano', `${IMG}/cafe-granos-saco.jpg`], ['Molido', `${IMG}/cafe-granos-bowl.jpg`], ['Blends', `${IMG}/cafe-bolsas-papel.jpg`], ['Accesorios', `${IMG}/cafe-set.jpg`]],
    cupon: { titulo: '15% llevando 1 kg', bajada: 'Se aplica al pagar. No se acumula con otras promos.', codigo: 'TUESTE15' },
    pie: { columnas: [['Comprar', ['En grano', 'Molido', 'Blends', 'Accesorios']], ['Ayuda', ['Envíos', 'Molienda', 'Contacto']], ['Legales', ['Términos', 'Privacidad']]], cierre: 'Tostaduría en Chacarita' },
    tema: {
      bg: '#FAF6F1', surf: '#FFFFFF', soft: '#F1E9E0', text: '#2B1D14', muted: '#7E6A5B', border: '#E6DACD',
      primary: '#6F4429', onPrimary: '#FFFFFF', accent: '#2F6B4F',
      fh: serif('DM Serif Display'), fb: sans('DM Sans'), radio: 6, oscuro: false,
      sombra: '0 18px 40px -20px rgba(111,68,41,0.38)',
    },
    slides: [
      { img: `${IMG}/cafe-cuchara.jpg`, kicker: 'Tostado esta semana', titulo: '−20%', bajada: 'en el blend de la casa', cta: 'Ver el blend' },
      { img: `${IMG}/cafe-bolsas-estante.jpg`, kicker: 'Origen único', titulo: '3x2', bajada: 'en bolsas de 250 g', cta: 'Ver el 3x2' },
      { img: `${IMG}/cafe-taza.jpg`, kicker: 'Envío gratis', titulo: '48 hs', bajada: 'desde $30.000', cta: 'Comprar ahora' },
    ],
    productos: [
      { nombre: 'Blend de la casa · 500 g', badge: 'Más vendido', badgeTono: 'verde', estrellas: 5, resenas: 241, tag: 'Chocolate y nuez · tueste medio', img: `${IMG}/cafe-bolsas-papel.jpg`, img2: `${IMG}/cafe-granos-mesa.jpg`, ...ar('$16.900', '$21.000', '$13.520', '$5.633') },
      { nombre: 'Colombia lavado · 250 g', badge: 'Origen único', badgeTono: 'violeta', estrellas: 5, resenas: 88, tag: 'Huila · 1.700 msnm · cítrico', img: `${IMG}/cafe-granos-saco.jpg`, img2: `${IMG}/cafe-derrame.jpg`, ...ar('$11.400', '$14.000', '$9.120', '$3.800') },
      { nombre: 'Molido para filtro · 250 g', estrellas: 4, resenas: 134, tag: 'Molienda media · V60 y Chemex', img: `${IMG}/cafe-granos-bowl.jpg`, img2: `${IMG}/cafe-cuchara-madera.jpg`, ...ar('$9.800', '$12.500', '$7.840', '$3.266') },
      { nombre: 'Prensa francesa 350 ml', badge: 'Accesorios', badgeTono: 'azul', estrellas: 5, resenas: 57, stock: 'Quedan 6', img: `${IMG}/cafe-set.jpg`, img2: `${IMG}/cafe-granos-taza.jpg`, ...ar('$34.000', '$42.000', '$27.200', '$11.333') },
    ],
  },
  {
    id: 'pinon',
    nombre: 'Piñón',
    para: 'Repuestos, autopartes, accesorios y herramientas',
    queCambia: 'Azul señal y naranja sobre gris acero, con Archivo y esquinas casi rectas. Categorías por rubro de taller (repuestos, neumáticos, herramientas, accesorios) y barra de confianza con factura A y garantía escrita.',
    secciones: ['Cartel corriendo', 'Carrusel', 'Barra de confianza', 'Destacados', 'Categorías', 'Más vendidos', 'Cupón'],
    marca: 'Piñón', tagline: 'Repuestos y accesorios para tu auto',
    layout: 'tienda',
    cartel: '✦ ENVÍO A TODO EL PAÍS EN 48 HS ✦ FACTURA A ✦ GARANTÍA ESCRITA',
    links: ['Inicio', 'Repuestos', 'Neumáticos', 'Herramientas', 'Accesorios'],
    confianza: [['Envío', '48 hs al país'], ['Factura A', 'para talleres'], ['Garantía', '6 meses'], ['Retiro', 'en el depósito']],
    categorias: [['Repuestos', `${IMG}/auto-repuestos.jpg`], ['Neumáticos', `${IMG}/auto-neumaticos.jpg`], ['Herramientas', `${IMG}/auto-tubos.jpg`], ['Accesorios', `${IMG}/auto-rueda.jpg`]],
    cupon: { titulo: '10% pagando por transferencia', bajada: 'Se aplica al pagar. No se acumula con otras promos.', codigo: 'PINON10' },
    pie: { columnas: [['Comprar', ['Repuestos', 'Neumáticos', 'Herramientas', 'Accesorios']], ['Talleres', ['Factura A', 'Cuenta corriente']], ['Ayuda', ['Envíos', 'Garantías', 'Contacto']]], cierre: 'Depósito en Avellaneda' },
    tema: {
      bg: '#F6F8FA', surf: '#FFFFFF', soft: '#EDF1F5', text: '#101820', muted: '#5C6B7A', border: '#D8E0E8',
      primary: '#0B4F9E', onPrimary: '#FFFFFF', accent: '#F97316',
      fh: sans('Archivo'), fb: sans('Inter'), radio: 4, oscuro: false,
      sombra: '0 16px 32px -18px rgba(11,79,158,0.40)',
    },
    slides: [
      { img: `${IMG}/auto-rueda.jpg`, kicker: 'Llantas y cubiertas', titulo: '−30%', bajada: 'en la segunda cubierta', cta: 'Ver neumáticos' },
      { img: `${IMG}/auto-taller-herramientas.jpg`, kicker: 'Herramientas', titulo: '12x', bajada: 'sin interés con tarjeta', cta: 'Ver herramientas' },
      { img: `${IMG}/auto-motor.jpg`, kicker: 'Envío al país', titulo: '48 hs', bajada: 'con seguimiento', cta: 'Comprar ahora' },
    ],
    productos: [
      { nombre: 'Juego de tubos 108 piezas', badge: 'Más vendido', badgeTono: 'azul', estrellas: 5, resenas: 164, tag: 'Encastre 1/4" y 1/2" · cromo vanadio', img: `${IMG}/auto-tubos.jpg`, img2: `${IMG}/auto-herramientas.jpg`, ...ar('$186.000', '$235.000', '$148.800', '$62.000') },
      { nombre: 'Cubierta 195/65 R15', badge: 'Envío gratis', badgeTono: 'verde', estrellas: 5, resenas: 97, tag: 'Índice 91H · dibujo asimétrico', img: `${IMG}/auto-neumaticos.jpg`, img2: `${IMG}/auto-rueda.jpg`, ...ar('$148.500', '$182.000', '$118.800', '$49.500') },
      { nombre: 'Llaves combinadas · 12 piezas', estrellas: 4, resenas: 73, tag: 'De 6 a 22 mm · acero forjado', img: `${IMG}/auto-llaves.jpg`, img2: `${IMG}/auto-piezas.jpg`, ...ar('$62.400', '$79.000', '$49.920', '$20.800') },
      { nombre: 'Kit de filtros para service', badge: 'Últimos 3', badgeTono: 'rojo', estrellas: 5, resenas: 118, stock: 'Quedan 3', tag: 'Aceite, aire y habitáculo', img: `${IMG}/auto-repuestos.jpg`, img2: `${IMG}/auto-maquina.jpg`, ...ar('$38.900', '$49.000', '$31.120', '$12.966') },
    ],
  },
  {
    id: 'circuito',
    nombre: 'Circuito',
    para: 'Tecnología, audio, periféricos y gaming',
    queCambia: 'La única con el header como panel lateral fijo: la marca, la navegación y las acciones de tienda quedan a la izquierda y todo lo demás scrollea al lado. El producto se muestra en fichas partidas —foto de un lado, ficha técnica y cuotas del otro— en vez de tarjetas, y las categorías van en lista con flecha. Grafito con violeta eléctrico y Space Grotesk.',
    secciones: ['Panel lateral fijo', 'Hero a sangre', 'Datos de compra', 'Fichas partidas', 'Categorías en lista', 'Cupón'],
    marca: 'Circuito', tagline: 'Tecnología, audio y periféricos',
    layout: 'circuito',
    cartel: '✦ 12 CUOTAS SIN INTERÉS ✦ GARANTÍA OFICIAL 12 MESES',
    links: ['Inicio', 'Audio', 'Periféricos', 'Notebooks', 'Smartwatch'],
    confianza: [['12 cuotas', 'sin interés'], ['Garantía', 'oficial 12 meses'], ['Envío gratis', 'desde $150.000'], ['Cambios', 'hasta 30 días']],
    categorias: [['Audio', `${IMG}/tech-auriculares.jpg`], ['Teclados', `${IMG}/tech-teclado-2.jpg`], ['Notebooks', `${IMG}/tech-notebook.jpg`], ['Smartwatch', `${IMG}/tech-reloj.jpg`]],
    cupon: { titulo: '8% pagando por transferencia', bajada: 'Se aplica al pagar. No se acumula con otras promos.', codigo: 'CIRCUITO8' },
    pie: { columnas: [['Comprar', ['Audio', 'Periféricos', 'Notebooks', 'Smartwatch']], ['Ayuda', ['Envíos', 'Garantía', 'Contacto']], ['Legales', ['Términos', 'Privacidad']]], cierre: 'Showroom en Once' },
    tema: {
      bg: '#0D0D12', surf: '#16161E', soft: '#121219', text: '#F4F4F7', muted: '#9A9AAB', border: '#26262F',
      primary: '#8B5CF6', onPrimary: '#FFFFFF', accent: '#38BDF8',
      fh: sans('Space Grotesk'), fb: sans('Space Grotesk'), radio: 14, oscuro: true,
      sombra: '0 22px 48px -24px rgba(139,92,246,0.50)',
    },
    slides: [
      { img: `${IMG}/tech-setup.jpg`, kicker: 'Setup completo', titulo: '12x', bajada: 'sin interés en todo el sitio', cta: 'Ver ofertas' },
      { img: `${IMG}/tech-auriculares-2.jpg`, kicker: 'Audio', titulo: '−35%', bajada: 'en auriculares con ANC', cta: 'Ver audio' },
      { img: `${IMG}/tech-teclado-3.jpg`, kicker: 'Periféricos', titulo: '3x2', bajada: 'en teclados y mouses', cta: 'Ver el 3x2' },
    ],
    productos: [
      { nombre: 'Auriculares ANC over-ear', badge: 'ANC 35 dB', badgeTono: 'violeta', estrellas: 5, resenas: 208, tag: '38 h de batería · driver de 50 mm', colores: ['#16161E', '#E4E4E7'], img: `${IMG}/tech-auriculares.jpg`, img2: `${IMG}/tech-auriculares-2.jpg`, ...ar('$268.000', '$329.000', '$214.400', '$89.333') },
      { nombre: 'Teclado mecánico 75%', badge: 'Hot-swap', badgeTono: 'azul', estrellas: 5, resenas: 156, tag: 'Switch lineal · doble shot PBT', colores: ['#0D0D12', '#8B5CF6'], img: `${IMG}/tech-teclado-2.jpg`, img2: `${IMG}/tech-teclado.jpg`, ...ar('$174.000', '$215.000', '$139.200', '$58.000') },
      { nombre: 'Mouse inalámbrico liviano', estrellas: 4, resenas: 92, tag: '54 g · sensor de 26.000 dpi', img: `${IMG}/tech-mouse.jpg`, img2: `${IMG}/tech-teclado-3.jpg`, ...ar('$96.500', '$124.000', '$77.200', '$32.166') },
      { nombre: 'Smartwatch con GPS', badge: 'Últimos 2', badgeTono: 'rojo', estrellas: 5, resenas: 143, stock: 'Quedan 2', tag: 'AMOLED de 1,9" · 14 días de batería', colores: ['#16161E', '#38BDF8'], img: `${IMG}/tech-reloj.jpg`, img2: `${IMG}/tech-camara.jpg`, ...ar('$312.000', '$389.000', '$249.600', '$104.000') },
    ],
  },
  {
    id: 'vera',
    nombre: 'Vera',
    para: 'Joyería en plata y oro, orfebrería, relojería',
    queCambia: 'Portada de catálogo impreso: el texto del hero va centrado ENCIMA de la foto, no a un costado, y las piezas se listan numeradas —01, 02, 03— con filete entre una y otra y el precio alineado a la derecha. No hay una sola grilla de productos en toda la página. Perla y oro viejo con Libre Baskerville.',
    secciones: ['Portada de catálogo', 'Servicios en filetes', 'Piezas numeradas', 'Índice de categorías', 'Cupón'],
    marca: 'Vera', tagline: 'Joyería en plata y oro, hecha a mano',
    layout: 'vera',
    cartel: '✦ GRABADO SIN CARGO ✦ ENVÍO ASEGURADO A TODO EL PAÍS',
    links: ['Inicio', 'Anillos', 'Collares', 'Aros', 'A pedido'],
    confianza: [['Envío', 'asegurado'], ['Grabado', 'sin cargo'], ['3 cuotas', 'sin interés'], ['Garantía', 'de por vida']],
    categorias: [['Anillos', `${IMG}/joya-anillo.jpg`], ['Collares', `${IMG}/joya-collar.jpg`], ['Aros', `${IMG}/joya-aros.jpg`], ['Pulseras', `${IMG}/joya-pulsera.jpg`]],
    cupon: { titulo: '10% en tu primera compra', bajada: 'Se aplica al pagar. No se acumula con otras promos.', codigo: 'VERA10' },
    pie: { columnas: [['Comprar', ['Anillos', 'Collares', 'Aros', 'Pulseras']], ['A pedido', ['Grabado', 'Talles', 'Encargues']], ['Ayuda', ['Envíos', 'Garantía', 'Contacto']]], cierre: 'Taller en San Telmo' },
    tema: {
      bg: '#FBFAF8', surf: '#FFFFFF', soft: '#F3F0EA', text: '#262220', muted: '#837B72', border: '#E7E1D8',
      primary: '#8C6B3F', onPrimary: '#FFFFFF', accent: '#A8927A',
      fh: serif('Libre Baskerville'), fb: sans('Lato'), radio: 2, oscuro: false,
      sombra: '0 18px 40px -22px rgba(140,107,63,0.35)',
    },
    slides: [
      { img: `${IMG}/joya-anillos-caja.jpg`, kicker: 'Hecho a mano', titulo: '−20%', bajada: 'en anillos de plata 925', cta: 'Ver anillos' },
      { img: `${IMG}/joya-cadena.jpg`, kicker: 'Grabado sin cargo', titulo: '3x2', bajada: 'en cadenas y dijes', cta: 'Ver el 3x2' },
      { img: `${IMG}/joya-set.jpg`, kicker: 'Envío asegurado', titulo: '48 hs', bajada: 'a todo el país', cta: 'Comprar ahora' },
    ],
    productos: [
      { nombre: 'Anillo Duna · plata 925', badge: 'Hecho a mano', badgeTono: 'verde', estrellas: 5, resenas: 118, img: `${IMG}/joya-anillo.jpg`, img2: `${IMG}/joya-anillo-piedras.jpg`, ...ar('$68.000', '$86.000', '$54.400', '$22.666') },
      { nombre: 'Collar Hilo · oro 18k', badge: 'A pedido', badgeTono: 'violeta', estrellas: 5, resenas: 34, img: `${IMG}/joya-collar.jpg`, img2: `${IMG}/joya-cadena.jpg`, ...ar('$420.000', '$520.000', '$336.000', '$140.000') },
      { nombre: 'Aros Gota · plata 925', estrellas: 5, resenas: 76, img: `${IMG}/joya-aros.jpg`, img2: `${IMG}/joya-set.jpg`, ...ar('$42.500', '$54.000', '$34.000', '$14.166') },
      { nombre: 'Pulsera Trenza · plata 925', badge: 'Últimas 5', badgeTono: 'rojo', estrellas: 4, resenas: 52, stock: 'Quedan 5', img: `${IMG}/joya-pulsera.jpg`, img2: `${IMG}/joya-pulsera-rosa.jpg`, ...ar('$56.900', '$71.000', '$45.520', '$18.966') },
    ],
  },
  {
    id: 'cobijo',
    nombre: 'Cobijo',
    para: 'Muebles, deco, textiles y bazar',
    queCambia: 'Se compra por ambiente, no por categoría suelta: el cuerpo son bloques que alternan lado —foto y texto, texto y foto— y cada uno se lleva sus dos productos abajo. El hero no tapa la foto con un degradé, le apoya una tarjeta blanca encima como una revista de decoración. Terracota sobre arena con Outfit.',
    secciones: ['Hero con tarjeta flotante', 'Ambientes en zigzag', 'Categorías', 'Cupón'],
    marca: 'Cobijo', tagline: 'Muebles, textiles y deco',
    layout: 'cobijo',
    cartel: '✦ ENVÍO GRATIS EN MUEBLES ✦ 6 CUOTAS SIN INTERÉS ✦ ARMADO SIN CARGO',
    links: ['Inicio', 'Muebles', 'Textiles', 'Deco', 'Plantas'],
    confianza: [['Envío gratis', 'en muebles'], ['6 cuotas', 'sin interés'], ['Armado', 'sin cargo'], ['Cambios', 'hasta 30 días']],
    categorias: [['Muebles', `${IMG}/casa-sillon.jpg`], ['Textiles', `${IMG}/casa-living-2.jpg`], ['Deco', `${IMG}/casa-ceramica.jpg`], ['Plantas', `${IMG}/casa-plantas.jpg`]],
    cupon: { titulo: '10% llevando dos productos o más', bajada: 'Se aplica al pagar. No se acumula con otras promos.', codigo: 'COBIJO10' },
    pie: { columnas: [['Comprar', ['Muebles', 'Textiles', 'Deco', 'Plantas']], ['Ayuda', ['Envíos', 'Armado', 'Cambios']], ['Legales', ['Términos', 'Privacidad']]], cierre: 'Showroom en Colegiales' },
    tema: {
      bg: '#FDFBF8', surf: '#FFFFFF', soft: '#F5EFE8', text: '#2A2320', muted: '#857A72', border: '#EAE1D7',
      primary: '#B5613C', onPrimary: '#FFFFFF', accent: '#4A6B62',
      fh: sans('Outfit'), fb: sans('Inter'), radio: 18, oscuro: false,
      sombra: '0 20px 42px -22px rgba(181,97,60,0.38)',
    },
    slides: [
      { img: `${IMG}/casa-living.jpg`, kicker: 'Temporada', titulo: '−40%', bajada: 'en sillones y sofás', cta: 'Ver muebles' },
      { img: `${IMG}/casa-deco.jpg`, kicker: 'Deco', titulo: '3x2', bajada: 'en cerámica y textiles', cta: 'Ver el 3x2' },
      { img: `${IMG}/casa-moderno.jpg`, kicker: 'Envío gratis', titulo: '48 hs', bajada: 'en CABA y GBA', cta: 'Comprar ahora' },
    ],
    productos: [
      { nombre: 'Sillón de una plaza en bouclé', badge: 'Envío gratis', badgeTono: 'verde', estrellas: 5, resenas: 64, colores: ['#EDE6DA', '#B5613C', '#2A2320'], img: `${IMG}/casa-sillon.jpg`, img2: `${IMG}/casa-interior.jpg`, ...ar('$398.000', '$498.000', '$318.400', '$132.666') },
      { nombre: 'Sofá de tres cuerpos', badge: 'Más vendido', badgeTono: 'azul', estrellas: 5, resenas: 41, colores: ['#C2703D', '#4A6B62', '#D6CFC4'], img: `${IMG}/casa-sofa-naranja.jpg`, img2: `${IMG}/casa-living-2.jpg`, ...ar('$845.000', '$1.060.000', '$676.000', '$281.666') },
      { nombre: 'Set de cerámica esmaltada', estrellas: 5, resenas: 127, img: `${IMG}/casa-ceramica.jpg`, img2: `${IMG}/casa-deco.jpg`, ...ar('$46.800', '$59.000', '$37.440', '$15.600') },
      { nombre: 'Planta de interior con maceta', badge: 'Últimas 4', badgeTono: 'rojo', estrellas: 4, resenas: 88, stock: 'Quedan 4', img: `${IMG}/casa-plantas.jpg`, img2: `${IMG}/casa-moderno.jpg`, ...ar('$32.400', '$41.000', '$25.920', '$10.800') },
    ],
  },
  {
    id: 'nitida',
    nombre: 'Nítida',
    para: 'Cosmética, skincare, perfumería',
    queCambia: 'Hero partido en dos mitades duras —color plano con el texto de un lado, foto del otro— en vez de texto encima de la foto. Los productos van en fichas horizontales de dos columnas, con las estrellas y el precio al lado de la foto, y las categorías en tarjetas altas con el nombre debajo. Verde salvia sobre blanco tiza con Manrope, sin nada de rosa.',
    secciones: ['Hero partido en dos', 'Beneficios en píldoras', 'Fichas horizontales', 'Categorías verticales', 'Segunda campaña'],
    marca: 'Nítida', tagline: 'Skincare y maquillaje, fórmulas cortas',
    layout: 'nitida',
    cartel: '✦ MUESTRAS DE REGALO EN TODA COMPRA ✦ ENVÍO GRATIS DESDE $45.000',
    links: ['Inicio', 'Skincare', 'Maquillaje', 'Cuerpo', 'Sets'],
    confianza: [['Envío gratis', 'desde $45.000'], ['Muestras', 'de regalo'], ['3 cuotas', 'sin interés'], ['Cambios', 'hasta 30 días']],
    categorias: [['Skincare', `${IMG}/belleza-cosmetica.jpg`], ['Maquillaje', `${IMG}/belleza-paletas.jpg`], ['Labiales', `${IMG}/belleza-labial.jpg`], ['Cuerpo', `${IMG}/belleza-spa.jpg`]],
    cupon: { titulo: '15% en tu primera compra', bajada: 'Se aplica al pagar. No se acumula con otras promos.', codigo: 'NITIDA15' },
    pie: { columnas: [['Comprar', ['Skincare', 'Maquillaje', 'Cuerpo', 'Sets']], ['Ayuda', ['Envíos', 'Cambios', 'Contacto']], ['Legales', ['Términos', 'Privacidad']]], cierre: 'Local en Recoleta' },
    tema: {
      bg: '#FBFCFA', surf: '#FFFFFF', soft: '#EFF3EE', text: '#1F2A24', muted: '#74857A', border: '#DDE5DC',
      primary: '#3F6B54', onPrimary: '#FFFFFF', accent: '#C98B7A',
      fh: sans('Manrope'), fb: sans('Manrope'), radio: 20, oscuro: false,
      sombra: '0 20px 42px -22px rgba(63,107,84,0.35)',
    },
    slides: [
      { img: `${IMG}/relato-modelo.jpg`, kicker: 'Rutina simple', titulo: '3x2', bajada: 'en toda la línea facial', cta: 'Ver skincare' },
      { img: `${IMG}/belleza-paleta-2.jpg`, kicker: 'Maquillaje', titulo: '−30%', bajada: 'en paletas y labiales', cta: 'Ver ofertas' },
      { img: `${IMG}/belleza-manos.jpg`, kicker: 'Envío gratis', titulo: '48 hs', bajada: 'desde $45.000', cta: 'Comprar ahora' },
    ],
    productos: [
      { nombre: 'Sérum de vitamina C · 30 ml', badge: 'Más vendido', badgeTono: 'verde', estrellas: 5, resenas: 372, img: `${IMG}/belleza-cosmetica.jpg`, img2: `${IMG}/relato-cosmetica.jpg`, ...ar('$36.500', '$45.000', '$29.200', '$12.166') },
      { nombre: 'Paleta de sombras · 12 tonos', badge: 'Vegano', badgeTono: 'violeta', estrellas: 5, resenas: 194, colores: ['#C98B7A', '#8C6B3F', '#3F6B54'], img: `${IMG}/belleza-paletas.jpg`, img2: `${IMG}/belleza-paleta-2.jpg`, ...ar('$31.900', '$39.000', '$25.520', '$10.633') },
      { nombre: 'Labial hidratante', estrellas: 5, resenas: 411, colores: ['#9F1239', '#C98B7A', '#7C2D3A'], img: `${IMG}/belleza-labial.jpg`, img2: `${IMG}/belleza-coral.jpg`, ...ar('$16.400', '$21.000', '$13.120', '$5.466') },
      { nombre: 'Crema corporal de karité', badge: 'Piel sensible', badgeTono: 'azul', estrellas: 4, resenas: 129, stock: 'Quedan 9', img: `${IMG}/belleza-spa.jpg`, img2: `${IMG}/belleza-maquillaje.jpg`, ...ar('$24.900', '$31.000', '$19.920', '$8.300') },
    ],
  },
]
