import { IMG, sans, serif, ar, type Plantilla } from './tipos'

// ─── Datos ───────────────────────────────────────────────────────────────────

export const PLANTILLAS: Plantilla[] = [
  {
    id: 'vidriera',
    nombre: 'Vidriera',
    para: 'Indumentaria, accesorios, venta masiva',
    queCambia: 'La más usada en Argentina y la que más vende. Cartel de promo corriendo, logo centrado con buscador, carrusel a pantalla completa con la promo a 132 px, y las fotos pegadas entre sí ocupando todo el ancho. Es la única con la ficha de precio completa: transferencia, cuotas y swatches.',
    secciones: ['Cartel corriendo', 'Carrusel automático', 'Barra de confianza', 'Destacados a sangre', 'Categorías', 'Más vendidos', 'Cupón'],
    marca: 'Travesía', tagline: 'Anteojos de sol y de descanso',
    layout: 'tienda',
    cartel: '✦ 3X1 + ENVÍO GRATIS',
    links: ['Inicio', '3x1 en gafas', 'Lentes de sol', 'De descanso', 'Fotocromáticos'],
    confianza: [['Envío gratis', 'desde $80.000'], ['3 cuotas', 'sin interés'], ['Cambios', 'hasta 30 días'], ['Garantía', '1 año']],
    categorias: [['Lentes de sol', `${IMG}/vidriera-anteojos.jpg`], ['De descanso', `${IMG}/vidriera-reloj.jpg`], ['Zapatillas', `${IMG}/vidriera-zapatilla-roja.jpg`], ['Accesorios', `${IMG}/moda-zapato.jpg`]],
    cupon: { titulo: '15% extra en tu primera compra', bajada: 'Se aplica al pagar. No se acumula con otras promos.', codigo: 'TRAVESIA15' },
    pie: { columnas: [['Comprar', ['Lentes de sol', 'De descanso', '3x1']], ['Ayuda', ['Envíos', 'Cambios', 'Contacto']], ['Legales', ['Términos', 'Privacidad']]], cierre: 'Defensa al consumidor' },
    tema: {
      bg: '#FFFFFF', surf: '#FFFFFF', soft: '#F6F7F9', text: '#0F172A', muted: '#64748B', border: '#E6E9EE',
      primary: '#0F172A', onPrimary: '#FFFFFF', accent: '#2563EB',
      fh: sans('Poppins'), fb: sans('Poppins'), radio: 0, oscuro: false,
      sombra: '0 18px 40px -18px rgba(15,23,42,0.28)',
    },
    slides: [
      { img: `${IMG}/vidriera-modelo.jpg`, kicker: 'Definí tu estilo', titulo: '3x1', bajada: 'en lentes calidad óptica', cta: 'Ver el 3x1' },
      { img: `${IMG}/vidriera-local.jpg`, kicker: 'Nueva temporada', titulo: '−40%', bajada: 'en toda la línea de sol', cta: 'Ver ofertas' },
      { img: `${IMG}/vidriera-anteojos.jpg`, kicker: 'Envío gratis', titulo: '48 hs', bajada: 'a todo el país', cta: 'Comprar ahora' },
    ],
    productos: [
      { nombre: 'Wave', badge: 'Blue Light Cut', badgeTono: 'azul', tag: '3X1', estrellas: 5, resenas: 128, colores: ['#111827', '#B45309', '#64748B'], img: `${IMG}/vidriera-anteojos.jpg`, img2: `${IMG}/vidriera-modelo.jpg`, ...ar('$109.000', '$189.000', '$87.200', '$36.333') },
      { nombre: 'Lyra', badge: 'Fotocromático', badgeTono: 'verde', tag: '3X1', estrellas: 5, resenas: 74, stock: 'Quedan 3', colores: ['#0F172A', '#D97706'], img: `${IMG}/vidriera-reloj.jpg`, img2: `${IMG}/vidriera-local.jpg`, ...ar('$97.990', '$142.000', '$78.392', '$32.663') },
      { nombre: 'Specter', badge: 'Polarizado', badgeTono: 'violeta', tag: '3X1', estrellas: 4, resenas: 41, colores: ['#DC2626', '#111827', '#F1F5F9'], img: `${IMG}/vidriera-zapatilla-roja.jpg`, img2: `${IMG}/vidriera-zapatilla-blanca.jpg`, ...ar('$98.990', '$159.000', '$79.192', '$32.996') },
      { nombre: 'Pixel', badge: 'UV400', badgeTono: 'azul', tag: '3X1', estrellas: 5, resenas: 96, colores: ['#F1F5F9', '#EA580C'], img: `${IMG}/vidriera-zapatilla-blanca.jpg`, img2: `${IMG}/moda-zapato.jpg`, ...ar('$89.000', '$139.000', '$71.200', '$29.666') },
    ],
  },
  {
    id: 'escaparate',
    nombre: 'Escaparate',
    para: 'Indumentaria, calzado, moda urbana',
    queCambia: 'Arranca con DOS campañas a pantalla partida, cada una con su público y su botón — la forma más común de separar mujer/hombre o temporada/básicos. Después trae "Comprá el look": una foto grande con puntos numerados sobre las prendas y la lista al costado con precio y botón. Muy visual, muy de marca de ropa.',
    secciones: ['Doble campaña partida', 'Tira de lo nuevo', 'Comprá el look', 'Categorías', 'Envío gratis'],
    marca: 'Distrito', tagline: 'Ropa urbana, temporada tras temporada',
    layout: 'escaparate',
    tema: {
      bg: '#FFFFFF', surf: '#FFFFFF', soft: '#F4F4F5', text: '#09090B', muted: '#71717A', border: '#E4E4E7',
      primary: '#09090B', onPrimary: '#FFFFFF', accent: '#DC2626',
      fh: sans('Montserrat'), fb: sans('Inter'), radio: 4, oscuro: false,
      sombra: '0 20px 46px -22px rgba(9,9,11,0.36)',
    },
    slides: [
      { img: `${IMG}/moda-mujer-invierno.jpg`, kicker: 'Mujer', titulo: 'Abrigos\nque abrigan', bajada: 'Nueva temporada', cta: 'Ver mujer' },
    ],
    productos: [
      { nombre: 'Campera puffer', badge: 'Nuevo', badgeTono: 'verde', estrellas: 5, resenas: 62, colores: ['#09090B', '#DC2626', '#D4D4D8'], img: `${IMG}/moda-mujer-invierno.jpg`, img2: `${IMG}/vidriera-modelo.jpg`, ...ar('$142.000', '$189.000', '$113.600', '$47.333') },
      { nombre: 'Zapatilla urbana', badge: 'Últimos talles', badgeTono: 'rojo', estrellas: 5, resenas: 148, colores: ['#DC2626', '#FFFFFF'], img: `${IMG}/vidriera-zapatilla-roja.jpg`, img2: `${IMG}/vidriera-zapatilla-blanca.jpg`, ...ar('$118.000', '$156.000', '$94.400', '$39.333') },
      { nombre: 'Zapato de cuero', estrellas: 4, resenas: 33, colores: ['#0F766E', '#78350F'], img: `${IMG}/moda-zapato.jpg`, img2: `${IMG}/vidriera-local.jpg`, ...ar('$186.000', '$232.000', '$148.800', '$62.000') },
      { nombre: 'Runner blanca', badge: 'Best seller', badgeTono: 'violeta', estrellas: 5, resenas: 211, colores: ['#FFFFFF', '#EA580C'], img: `${IMG}/vidriera-zapatilla-blanca.jpg`, img2: `${IMG}/vidriera-zapatilla-roja.jpg`, ...ar('$134.000', '$168.000', '$107.200', '$44.666') },
    ],
  },
  {
    id: 'mosaico',
    nombre: 'Mosaico',
    para: 'Casa, deco, tiendas con muchas categorías',
    queCambia: 'La única sin hero: arranca con un muro de bloques de distinta altura, uno grande de campaña y cuatro de categoría con su porcentaje. Los productos van compactos, cinco por fila, con lo justo. Sirve cuando vendés cosas variadas y no hay UNA sola para destacar.',
    secciones: ['Sin hero', 'Muro de bloques', 'Grilla compacta de 5', 'Franja de envío', 'Marcas'],
    marca: 'Mercado Sur', tagline: 'Casa, cocina y jardín',
    layout: 'mosaico',
    tema: {
      bg: '#FAFAF9', surf: '#FFFFFF', soft: '#F1F1EF', text: '#1C1917', muted: '#78716C', border: '#E4E4E1',
      primary: '#0D9488', onPrimary: '#FFFFFF', accent: '#F59E0B',
      fh: sans('Montserrat'), fb: sans('Inter'), radio: 16, oscuro: false,
      sombra: '0 16px 38px -20px rgba(28,25,23,0.30)',
    },
    slides: [
      { img: `${IMG}/casa-living.jpg`, kicker: 'Temporada', titulo: 'Todo para\nrenovar la casa', bajada: 'Hasta 40% en cocina, textil y jardín.', cta: 'Ver ofertas' },
    ],
    productos: [
      { nombre: 'Set de cerámica esmaltada', badge: 'Envío gratis', badgeTono: 'verde', estrellas: 5, resenas: 62, colores: ['#D6D3D1', '#78716C'], img: `${IMG}/casa-ceramica.jpg`, img2: `${IMG}/casa-deco.jpg`, ...ar('$142.000', '$198.000', '$113.600', '$47.333') },
      { nombre: 'Sillón Nórdico crema', estrellas: 4, resenas: 18, colores: ['#F5F5F4', '#292524'], img: `${IMG}/casa-sillon.jpg`, img2: `${IMG}/casa-sofa-naranja.jpg`, ...ar('$486.900', '$620.000', '$389.520', '$162.300') },
      { nombre: 'Planta de interior + maceta', badge: 'Últimas 4', badgeTono: 'rojo', estrellas: 5, resenas: 31, stock: 'Quedan 4', img: `${IMG}/casa-plantas.jpg`, img2: `${IMG}/casa-deco.jpg`, ...ar('$28.500', '$38.000', '$22.800', '$9.500') },
      { nombre: 'Sofá de tres cuerpos', estrellas: 5, resenas: 47, colores: ['#EA580C', '#1C1917', '#D6D3D1'], img: `${IMG}/casa-sofa-naranja.jpg`, img2: `${IMG}/casa-living-2.jpg`, ...ar('$880.000', '$1.150.000', '$704.000', '$293.333') },
    ],
  },
  {
    id: 'premium',
    nombre: 'Premium',
    para: 'Joyería, relojería, accesorios de alta gama',
    queCambia: 'Fondo carbón con dorado y mucho aire alrededor de cada pieza. El producto se presenta de a una, grande y con foco, no en grilla apretada. Precios en dorado, sin tachados ni carteles de oferta: acá el argumento es la pieza, no el descuento.',
    secciones: ['Header dorado', 'Hero con foco sobre negro', 'Categorías oscuras', 'Piezas de a tres', 'Certificaciones', 'Grabado personalizado'],
    marca: 'Solano', tagline: 'Joyería en oro 18k, hecha a pedido',
    layout: 'premium',
    tema: {
      bg: '#0C0A09', surf: '#171412', soft: '#12100E', text: '#F5F1EA', muted: '#A8A29E', border: '#2A2521',
      primary: '#C9A227', onPrimary: '#1C1917', accent: '#E0C060',
      fh: serif('Cormorant Garamond'), fb: sans('Lato'), radio: 2, oscuro: true,
      sombra: '0 24px 60px -28px rgba(201,162,39,0.35)',
    },
    slides: [
      { img: `${IMG}/joya-pulsera.jpg`, kicker: 'Colección Aurora', titulo: 'Piezas que\nse heredan', bajada: 'Oro 18k y piedras seleccionadas a mano. Cada pieza sale con su certificado.', cta: 'Ver la colección' },
    ],
    productos: [
      { nombre: 'Anillo Aurora · oro 18k', precio: '$1.240.000', badge: 'Hecho a pedido', badgeTono: 'verde', estrellas: 5, resenas: 46, img: `${IMG}/joya-anillo.jpg`, img2: `${IMG}/joya-anillos-caja.jpg` },
      { nombre: 'Cadena Aurora · oro 18k', precio: '$1.680.000', badge: 'Única', badgeTono: 'violeta', estrellas: 5, resenas: 12, img: `${IMG}/joya-cadena.jpg`, img2: `${IMG}/joya-pulsera.jpg` },
      { nombre: 'Aros Duna · oro y turquesa', precio: '$980.000', estrellas: 5, resenas: 31, img: `${IMG}/joya-set.jpg`, img2: `${IMG}/joya-pulsera-rosa.jpg` },
      { nombre: 'Reloj automático acero', precio: '$2.150.000', estrellas: 5, resenas: 58, img: `${IMG}/joya-reloj.jpg`, img2: `${IMG}/joya-pulsera.jpg` },
    ],
  },
  {
    id: 'nocturno',
    nombre: 'Nocturno',
    para: 'Gaming, audio, componentes',
    queCambia: 'Oscura y con datos en vez de frases. Barra de lanzamiento con contador, el producto flotando sobre un foco de luz, categorías con su cantidad de artículos, carrusel horizontal con specs adentro de cada tarjeta, armador de setup en tres pasos y comparativa de tres modelos.',
    secciones: ['Contador de lanzamiento', 'Hero con foco de luz', 'Categorías', 'Carrusel con specs', 'Armá tu setup', 'Comparativa', 'Números grandes'],
    marca: 'Vector', tagline: 'Periféricos y audio, sin vueltas',
    layout: 'nocturno',
    tema: {
      bg: '#0B1120', surf: '#131C2E', soft: '#101827', text: '#F1F5F9', muted: '#94A3B8', border: '#1E293B',
      primary: '#22D3EE', onPrimary: '#04121A', accent: '#818CF8',
      fh: sans('Geist'), fb: sans('Geist'), radio: 10, oscuro: true,
      sombra: '0 22px 50px -26px rgba(34,211,238,0.45)',
    },
    slides: [
      { img: `${IMG}/tech-auriculares.jpg`, kicker: 'Nuevo · V-90 Pro', titulo: 'Auriculares\nV-90 Pro', bajada: 'Driver de 50 mm, 38 horas de batería y cancelación activa de 35 dB.', cta: 'Ver ficha completa' },
    ],
    productos: [
      { nombre: 'Teclado 75% hot-swap', badge: 'Switch lineal', badgeTono: 'azul', estrellas: 5, resenas: 143, colores: ['#111827', '#F1F5F9'], img: `${IMG}/tech-teclado-2.jpg`, img2: `${IMG}/tech-teclado.jpg`, ...ar('$189.000', '$229.000', '$151.200', '$63.000') },
      { nombre: 'Mouse inalámbrico 8K', badge: '54 g', badgeTono: 'violeta', estrellas: 4, resenas: 88, img: `${IMG}/tech-mouse.jpg`, img2: `${IMG}/tech-setup.jpg`, ...ar('$142.000', '$168.000', '$113.600', '$47.333') },
      { nombre: 'Auriculares over-ear', badge: 'ANC 35 dB', badgeTono: 'verde', estrellas: 5, resenas: 211, stock: 'Quedan 2', img: `${IMG}/tech-auriculares-2.jpg`, img2: `${IMG}/tech-auriculares.jpg`, ...ar('$249.000', '$310.000', '$199.200', '$83.000') },
      { nombre: 'Setup completo gamer', badge: 'Combo', badgeTono: 'rojo', estrellas: 5, resenas: 37, img: `${IMG}/tech-setup.jpg`, img2: `${IMG}/tech-notebook.jpg`, ...ar('$1.240.000', '$1.520.000', '$992.000', '$413.333') },
    ],
  },
  {
    id: 'glow',
    nombre: 'Glow',
    para: 'Cosmética, skincare, perfumería',
    queCambia: 'Rosa y nude con degradés suaves, pero vendedora: la rutina se muestra con los tres productos numerados y su precio, no con párrafos. Trae grilla de best sellers con estrellas, un antes y después, y una galería de Instagram al pie. Bonita sin dejar de ser tienda.',
    secciones: ['Hero con degradé', 'Sellos de producto', 'Rutina en 3 productos', 'Best sellers', 'Antes y después', 'Galería de Instagram'],
    marca: 'Aura', tagline: 'Skincare simple, resultados visibles',
    layout: 'glow',
    tema: {
      bg: '#FFF9FB', surf: '#FFFFFF', soft: '#FDEEF3', text: '#3B1027', muted: '#9B6B80', border: '#F6DCE6',
      primary: '#DB2777', onPrimary: '#FFFFFF', accent: '#C084FC',
      fh: sans('Poppins'), fb: sans('Lato'), radio: 22, oscuro: false,
      sombra: '0 20px 46px -22px rgba(219,39,119,0.30)',
    },
    slides: [
      { img: `${IMG}/belleza-labial.jpg`, kicker: 'Nueva línea', titulo: 'Tu piel,\nsin filtros', bajada: 'Fórmulas cortas, activos en la dosis que sirve.', cta: 'Ver la línea' },
    ],
    productos: [
      { nombre: 'Sérum de vitamina C', badge: 'Best seller', badgeTono: 'violeta', estrellas: 5, resenas: 428, precio: '$34.000', antes: '$42.000', img: `${IMG}/belleza-cosmetica.jpg`, img2: `${IMG}/relato-cosmetica.jpg` },
      { nombre: 'Paleta de sombras', badge: '12 tonos', badgeTono: 'violeta', estrellas: 5, resenas: 216, precio: '$28.500', colores: ['#B45309', '#DB2777', '#7C3AED'], img: `${IMG}/belleza-paletas.jpg`, img2: `${IMG}/belleza-paleta-2.jpg` },
      { nombre: 'Labial hidratante', badge: 'Vegano', badgeTono: 'verde', estrellas: 5, resenas: 519, precio: '$14.900', colores: ['#DC2626', '#DB2777', '#9F1239'], img: `${IMG}/belleza-coral.jpg`, img2: `${IMG}/belleza-maquillaje.jpg` },
      { nombre: 'Crema de noche', badge: 'Piel sensible', badgeTono: 'azul', estrellas: 4, resenas: 137, precio: '$26.000', img: `${IMG}/relato-cosmetica.jpg`, img2: `${IMG}/belleza-cosmetica.jpg` },
    ],
  },
  {
    id: 'papeleria',
    nombre: 'Papelería',
    para: 'Librería, papelería, arte, insumos de oficina',
    queCambia: 'La única que arranca con el buscador como protagonista: en una librería nadie navega, viene a buscar algo puntual. Hero con un campo grande y búsquedas frecuentes, categorías en pastillas y un armador de lista escolar con casilleros y total, que ninguna otra tiene.',
    secciones: ['Buscador protagonista', 'Búsquedas frecuentes', 'Categorías en pastillas', 'Armá tu lista escolar', 'Grilla de 4', 'Vuelta a clases'],
    marca: 'Renglón', tagline: 'Librería, papelería y arte',
    layout: 'papeleria',
    tema: {
      bg: '#FAF7F0', surf: '#FFFFFF', soft: '#F3EEE3', text: '#1C1917', muted: '#78716C', border: '#E7E0D2',
      primary: '#1D4ED8', onPrimary: '#FFFFFF', accent: '#F59E0B',
      fh: sans('Poppins'), fb: sans('Inter'), radio: 12, oscuro: false,
      sombra: '0 16px 34px -20px rgba(29,78,216,0.35)',
    },
    slides: [
      { img: `${IMG}/libre-escolar.jpg`, kicker: 'Vuelta a clases', titulo: '¿Qué necesitás?', bajada: 'Más de 4.000 artículos de librería, papelería y arte. Buscá por nombre, marca o código.', cta: 'Buscar' },
    ],
    productos: [
      { nombre: 'Cuaderno tapa dura A4', badge: 'Más vendido', badgeTono: 'azul', estrellas: 5, resenas: 214, colores: ['#1E3A8A', '#B91C1C', '#065F46'], img: `${IMG}/libre-cuaderno.jpg`, img2: `${IMG}/libre-anotador.jpg`, ...ar('$4.900', '$6.200', '$3.920', '$1.633') },
      { nombre: 'Set 24 lápices de colores', badge: 'Escolar', badgeTono: 'verde', estrellas: 5, resenas: 168, img: `${IMG}/libre-lapices.jpg`, img2: `${IMG}/libre-escolar.jpg`, ...ar('$8.700', '$11.000', '$6.960', '$2.900') },
      { nombre: 'Mochila reforzada 18"', estrellas: 4, resenas: 92, stock: 'Quedan 6', colores: ['#1F2937', '#0F766E'], img: `${IMG}/libre-mochila.jpg`, img2: `${IMG}/libre-escolar.jpg`, ...ar('$38.500', '$48.000', '$30.800', '$12.833') },
      { nombre: 'Lapicera roller punta fina', badge: 'Oficina', badgeTono: 'violeta', estrellas: 5, resenas: 341, img: `${IMG}/libre-lapicera.jpg`, img2: `${IMG}/libre-cuaderno.jpg`, ...ar('$2.400', '$3.100', '$1.920', '$800') },
    ],
  },
  {
    id: 'corralon',
    nombre: 'Corralón',
    para: 'Ferretería, corralón, materiales, pinturería',
    queCambia: 'Pensada para catálogos enormes: barra de doce departamentos siempre visible, hero partido en tres avisos operativos (retiro, envío, cuenta corriente) y fichas de producto con tabla de especificaciones. Trae una calculadora de materiales que ninguna otra plantilla tiene.',
    secciones: ['Barra de departamentos', 'Hero partido en tres', 'Calculadora de materiales', 'Fichas con especificaciones', 'Retiro en sucursal'],
    marca: 'Bulón', tagline: 'Ferretería y corralón desde 1972',
    layout: 'corralon',
    tema: {
      bg: '#FFFFFF', surf: '#FFFFFF', soft: '#F5F5F4', text: '#0C0A09', muted: '#57534E', border: '#D6D3D1',
      primary: '#111827', onPrimary: '#FACC15', accent: '#FACC15',
      fh: sans('Montserrat'), fb: sans('Inter'), radio: 4, oscuro: false,
      sombra: '0 14px 30px -18px rgba(12,10,9,0.45)',
    },
    slides: [
      { img: `${IMG}/ferre-corralon.jpg`, kicker: 'Retirá hoy', titulo: 'Todo para la obra\ny el arreglo', bajada: 'Nueve sucursales con stock propio. Comprás online y retirás en el día.', cta: 'Ver departamentos' },
    ],
    productos: [
      { nombre: 'Taladro percutor 750W', badge: 'Envío gratis', badgeTono: 'verde', estrellas: 5, resenas: 128, tag: '13 mm · 2.900 rpm · 2 velocidades', img: `${IMG}/ferre-taladro.jpg`, img2: `${IMG}/ferre-taladro-rojo.jpg`, ...ar('$132.000', '$168.000', '$105.600', '$44.000') },
      { nombre: 'Juego de formones 6 piezas', estrellas: 5, resenas: 64, tag: 'Acero al cromo · 6 a 32 mm · estuche', img: `${IMG}/ferre-formones.jpg`, img2: `${IMG}/ferre-pared.jpg`, ...ar('$46.800', '$59.000', '$37.440', '$15.600') },
      { nombre: 'Látex interior 20 L', badge: 'Más vendido', badgeTono: 'azul', estrellas: 4, resenas: 203, tag: 'Rinde 12 m² por litro · lavable · blanco', img: `${IMG}/ferre-pintura.jpg`, img2: `${IMG}/ferre-cocina.jpg`, ...ar('$89.900', '$112.000', '$71.920', '$29.966') },
      { nombre: 'Amoladora angular 4½"', estrellas: 4, resenas: 87, stock: 'Últimas 3', tag: '900W · 11.000 rpm · con disco', img: `${IMG}/ferre-electronica.jpg`, img2: `${IMG}/ferre-canos.jpg`, ...ar('$74.500', '$95.000', '$59.600', '$24.833') },
    ],
  },
  {
    id: 'atleta',
    nombre: 'Atleta',
    para: 'Running, entrenamiento, ciclismo, indumentaria deportiva',
    queCambia: 'Negro y lima, tipografía condensada en mayúsculas y foto a sangre de borde a borde. El catálogo no se muestra en grilla sino en tiras horizontales por disciplina que se arrastran con el dedo, y cierra con los números de la comunidad. Es la más agresiva de las doce.',
    secciones: ['Hero a sangre', 'Tiras por disciplina', 'Fichas con tecnología', 'Números de la comunidad', 'Guía de talles'],
    marca: 'Ritmo', tagline: 'Running, fuerza y ciclismo',
    layout: 'atleta',
    tema: {
      bg: '#0A0A0A', surf: '#141414', soft: '#171717', text: '#FAFAFA', muted: '#A3A3A3', border: '#262626',
      primary: '#BEF264', onPrimary: '#0A0A0A', accent: '#F97316',
      fh: sans('Oswald'), fb: sans('Inter'), radio: 3, oscuro: true,
      sombra: '0 20px 44px -22px rgba(190,242,100,0.35)',
    },
    slides: [
      { img: `${IMG}/dep-correr.jpg`, kicker: 'Temporada 26', titulo: 'NO EMPIEZA\nMAÑANA', bajada: 'Zapatillas, indumentaria técnica y accesorios para entrenar todos los días del año.', cta: 'Ver la colección' },
    ],
    productos: [
      { nombre: 'Zapatilla de running Vento', badge: 'Nueva', badgeTono: 'verde', estrellas: 5, resenas: 176, tag: 'Amortiguación de 32 mm · 218 g', colores: ['#DC2626', '#171717', '#BEF264'], img: `${IMG}/dep-zapatilla-roja.jpg`, img2: `${IMG}/dep-zapatilla.jpg`, ...ar('$189.000', '$240.000', '$151.200', '$63.000') },
      { nombre: 'Calza técnica compresión', estrellas: 5, resenas: 214, tag: 'Tejido de secado rápido · bolsillo lateral', colores: ['#171717', '#525252'], img: `${IMG}/dep-estirar.jpg`, img2: `${IMG}/dep-abdominales.jpg`, ...ar('$62.000', '$78.000', '$49.600', '$20.666') },
      { nombre: 'Bicicleta urbana fija', badge: 'Últimas 2', badgeTono: 'rojo', estrellas: 5, resenas: 41, stock: 'Quedan 2', tag: 'Cuadro de acero · rodado 28', img: `${IMG}/dep-bici.jpg`, img2: `${IMG}/dep-pista.jpg`, ...ar('$540.000', '$690.000', '$432.000', '$180.000') },
      { nombre: 'Set de mancuernas 2 × 10 kg', estrellas: 4, resenas: 98, tag: 'Recubiertas en goma · agarre moleteado', img: `${IMG}/dep-pesas.jpg`, img2: `${IMG}/dep-sentadilla.jpg`, ...ar('$118.000', '$149.000', '$94.400', '$39.333') },
    ],
  },
  {
    id: 'patitas',
    nombre: 'Patitas',
    para: 'Pet shop, alimento, accesorios, veterinaria',
    queCambia: 'Crema y coral, todo redondeado, con las fotos en círculo. Arranca preguntando para quién comprás y ofrece tres círculos grandes (perro, gato, otros) en vez de un menú de categorías: es como se compra en un pet shop, pensando en el animal y no en el rubro.',
    secciones: ['¿Para quién comprás?', 'Hero redondeado', 'Fichas con badge', 'Categorías en círculo'],
    marca: 'Colita', tagline: 'Todo para tu perro y tu gato',
    layout: 'patitas',
    tema: {
      bg: '#FFF9F5', surf: '#FFFFFF', soft: '#FFF0E6', text: '#2D1B12', muted: '#8B7268', border: '#F2DFD1',
      primary: '#F97316', onPrimary: '#FFFFFF', accent: '#22C55E',
      fh: sans('Nunito'), fb: sans('Nunito'), radio: 20, oscuro: false,
      sombra: '0 20px 40px -22px rgba(249,115,22,0.4)',
    },
    slides: [
      { img: `${IMG}/masc-perro-rosa.jpg`, kicker: 'Envío en el día', titulo: 'Lo mejor\npara tu compañero', bajada: 'Alimento, juguetes, camas y accesorios elegidos por veterinarios. Llega hoy si comprás antes de las 14.', cta: 'Empezar a comprar' },
    ],
    productos: [
      { nombre: 'Alimento premium perro adulto 15 kg', badge: 'Más vendido', badgeTono: 'verde', estrellas: 5, resenas: 312, img: `${IMG}/masc-entrega.jpg`, img2: `${IMG}/masc-perro.jpg`, ...ar('$74.900', '$92.000', '$59.920', '$24.966') },
      { nombre: 'Cama redonda desenfundable', estrellas: 5, resenas: 147, colores: ['#F97316', '#78716C', '#22C55E'], img: `${IMG}/masc-collie.jpg`, img2: `${IMG}/masc-perros.jpg`, ...ar('$56.000', '$71.000', '$44.800', '$18.666') },
      { nombre: 'Rascador de sisal con plataforma', badge: 'Gatos', badgeTono: 'violeta', estrellas: 5, resenas: 89, img: `${IMG}/masc-gato.jpg`, img2: `${IMG}/masc-gato-naranja.jpg`, ...ar('$42.300', '$54.000', '$33.840', '$14.100') },
      { nombre: 'Kit de juguetes mordillo', estrellas: 4, resenas: 205, stock: 'Quedan 8', img: `${IMG}/masc-bulldog.jpg`, img2: `${IMG}/masc-pug.jpg`, ...ar('$18.900', '$24.000', '$15.120', '$6.300') },
    ],
  },
  {
    id: 'bodega',
    nombre: 'Bodega',
    para: 'Vinotecas, bebidas, bodegas, delicatessen',
    queCambia: 'Borgoña y terracota. La sección central no tiene una sola foto: es una lista tipográfica de varietales, como la carta de un restaurante. Las botellas se muestran altas y angostas sobre tarjetas color crema que recortan contra el fondo oscuro, y cierra con maridajes.',
    secciones: ['Índice editorial', 'Lista de varietales sin fotos', 'Botellas altas sobre crema', 'Maridajes'],
    marca: 'Cepa', tagline: 'Vinos de autor y bodegas chicas',
    layout: 'bodega',
    tema: {
      bg: '#1A0F12', surf: '#241419', soft: '#201216', text: '#F5EDE6', muted: '#A99188', border: '#3A2228',
      primary: '#D4A373', onPrimary: '#1A0F12', accent: '#9F1239',
      fh: serif('Cormorant Garamond'), fb: sans('Lato'), radio: 0, oscuro: true,
      sombra: '0 24px 52px -26px rgba(212,163,115,0.35)',
    },
    slides: [
      { img: `${IMG}/vino-uvas.jpg`, kicker: 'Selección de octubre', titulo: 'Doce bodegas\nque no vas a\nencontrar en el súper', bajada: 'Producciones cortas del Valle de Uco, Salta y la Patagonia. Cada etiqueta con su ficha de cata.', cta: 'Ver la selección' },
    ],
    productos: [
      { nombre: 'Malbec de altura 2021', precio: '$28.400', estrellas: 5, resenas: 64, tag: 'Valle de Uco · 1.100 msnm', img: `${IMG}/vino-botella.jpg`, img2: `${IMG}/vino-oscuro.jpg` },
      { nombre: 'Cabernet Franc 2020', precio: '$34.900', badge: 'Últimas 6', badgeTono: 'rojo', estrellas: 5, resenas: 38, tag: 'Agrelo · guarda 12 meses', img: `${IMG}/vino-estante.jpg`, img2: `${IMG}/vino-servir-copa.jpg` },
      { nombre: 'Pinot Noir patagónico 2022', precio: '$41.200', estrellas: 5, resenas: 27, tag: 'Río Negro · producción de 3.000 botellas', img: `${IMG}/vino-oscuro.jpg`, img2: `${IMG}/vino-botella.jpg` },
      { nombre: 'Espumante método tradicional', precio: '$24.800', estrellas: 4, resenas: 51, tag: '18 meses sobre lías', img: `${IMG}/vino-brindis.jpg`, img2: `${IMG}/vino-copas-luz.jpg` },
    ],
  },
  {
    id: 'crecer',
    nombre: 'Crecer',
    para: 'Bebés, primera infancia, juguetería, ropa infantil',
    queCambia: 'Pastel, muy redondeada y con mucho aire. No se navega por categoría sino por EDAD, en una línea de tiempo horizontal con puntos (0-6 m, 6-12 m, 1-2 años…), porque es como compra el que regala: sabe los meses que tiene, no el rubro que busca.',
    secciones: ['Línea de tiempo por edad', 'Hero suave', 'Certificaciones'],
    marca: 'Nube', tagline: 'Para los primeros años',
    layout: 'crecer',
    tema: {
      bg: '#FFFDFB', surf: '#FFFFFF', soft: '#F4F7FA', text: '#33302E', muted: '#8A8580', border: '#EAE6E1',
      primary: '#7FA9C9', onPrimary: '#FFFFFF', accent: '#F0B49B',
      fh: sans('Quicksand'), fb: sans('Quicksand'), radio: 24, oscuro: false,
      sombra: '0 22px 44px -24px rgba(127,169,201,0.45)',
    },
    slides: [
      { img: `${IMG}/bebe-oso.jpg`, kicker: 'Otoño invierno', titulo: 'Suave desde\nel primer día', bajada: 'Algodón orgánico certificado, sin tinturas agresivas y con costuras planas. Pensado para pieles que recién empiezan.', cta: 'Ver por edad' },
    ],
    productos: [
      { nombre: 'Enterito de algodón orgánico', badge: 'Orgánico', badgeTono: 'verde', estrellas: 5, resenas: 186, colores: ['#F0B49B', '#7FA9C9', '#E8E4DF'], img: `${IMG}/bebe-oso.jpg`, img2: `${IMG}/bebe-ropa.jpg`, ...ar('$24.900', '$31.000', '$19.920', '$8.300') },
      { nombre: 'Tren de madera 24 piezas', badge: 'Sin tóxicos', badgeTono: 'azul', estrellas: 5, resenas: 94, img: `${IMG}/bebe-tren.jpg`, img2: `${IMG}/bebe-juguetes.jpg`, ...ar('$38.500', '$47.000', '$30.800', '$12.833') },
      { nombre: 'Manta de algodón con capucha', estrellas: 5, resenas: 132, colores: ['#F4F7FA', '#F0B49B'], img: `${IMG}/bebe-pies.jpg`, img2: `${IMG}/bebe-verano.jpg`, ...ar('$29.700', '$36.000', '$23.760', '$9.900') },
      { nombre: 'Set de primeros juguetes', estrellas: 4, resenas: 78, stock: 'Quedan 5', img: `${IMG}/bebe-juguetes.jpg`, img2: `${IMG}/bebe-nena.jpg`, ...ar('$21.400', '$27.000', '$17.120', '$7.133') },
    ],
  },
]
